-- Source of truth: sdd/wip/20260921-single-tenant-installation-baseline/2-technical/data-model-v1.md
-- TASK-002: core single-tenant baseline only; no BlackStore adapter objects.

CREATE TABLE installation_settings (
 installation_id SMALLINT PRIMARY KEY DEFAULT 1 CHECK(installation_id=1), business_name VARCHAR(160) NOT NULL,
 allowed_host VARCHAR(253) NOT NULL UNIQUE, currency CHAR(3) NOT NULL DEFAULT 'ARS', timezone VARCHAR(64) NOT NULL DEFAULT 'America/Argentina/Buenos_Aires',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(currency='ARS')
);
-- Provisioning inserts the sole row with installation_id=1; application startup fails closed if it is absent and no merchant selector exists.
CREATE TABLE capability_modules (
 module_code VARCHAR(40) PRIMARY KEY, scope_kind VARCHAR(24) NOT NULL DEFAULT 'INSTALLATION', future_optional BOOLEAN NOT NULL DEFAULT FALSE,
 CHECK(module_code IN ('STOREFRONT','CATALOG','PROFILE_CONTENT','PAYMENTS_MP','MANUAL_FULFILLMENT','MARKETPLACE_ML','MANUAL_PROMOTIONS','ML_COMPETITION_INSIGHTS','ML_PRICE_AUTOMATION','ML_PROMOTION_ORCHESTRATOR','WEB_CROSS_SELL_DISCOUNTS','COMMERCIAL_CALENDAR','FAVORITES','LOYALTY','CARRIERS','ML_VIRTUAL_KITS')),
 CHECK(scope_kind='INSTALLATION')
);
CREATE TABLE capability_actions (
 module_code VARCHAR(40) NOT NULL REFERENCES capability_modules(module_code) ON DELETE RESTRICT, action_code VARCHAR(64) NOT NULL, allows_write BOOLEAN NOT NULL,
 PRIMARY KEY(module_code, action_code)
);
CREATE TABLE module_configurations (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, module_code VARCHAR(40) NOT NULL REFERENCES capability_modules(module_code) ON DELETE RESTRICT,
 scope_kind VARCHAR(24) NOT NULL DEFAULT 'INSTALLATION', scope_key VARCHAR(64) NOT NULL DEFAULT 'DEFAULT', state VARCHAR(16) NOT NULL DEFAULT 'DISABLED', config_version INTEGER NOT NULL DEFAULT 1, config JSONB NOT NULL DEFAULT '{}'::jsonb, updated_by BIGINT NULL,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(module_code,scope_kind,scope_key), CHECK(scope_kind='INSTALLATION'), CHECK(scope_key='DEFAULT'), CHECK(config_version>0), CHECK(state IN ('DISABLED','READ_ONLY','ACTIVE','PAUSED','ERROR')), CHECK(jsonb_typeof(config)='object')
);
CREATE TABLE capability_kill_switches (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, module_code VARCHAR(40) NOT NULL, action_code VARCHAR(64) NOT NULL,
 scope_kind VARCHAR(24) NOT NULL DEFAULT 'INSTALLATION', scope_key VARCHAR(64) NOT NULL DEFAULT 'DEFAULT', owner VARCHAR(160) NOT NULL, reason VARCHAR(500) NOT NULL, expires_at TIMESTAMPTZ NOT NULL, removal_ticket VARCHAR(100) NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), removed_at TIMESTAMPTZ NULL,
 FOREIGN KEY(module_code,action_code) REFERENCES capability_actions(module_code,action_code) ON DELETE RESTRICT,
 CHECK(scope_kind='INSTALLATION'), CHECK(scope_key='DEFAULT'), CHECK(expires_at > created_at), CHECK((active AND removed_at IS NULL) OR (NOT active AND removed_at IS NOT NULL))
);
CREATE UNIQUE INDEX uq_active_capability_kill_switch ON capability_kill_switches(module_code,action_code,scope_kind,scope_key) WHERE active;
INSERT INTO capability_modules(module_code,future_optional) VALUES
 ('STOREFRONT',FALSE),('CATALOG',FALSE),('PROFILE_CONTENT',FALSE),('PAYMENTS_MP',FALSE),('MANUAL_FULFILLMENT',FALSE),('MARKETPLACE_ML',FALSE),('MANUAL_PROMOTIONS',FALSE),
 ('ML_COMPETITION_INSIGHTS',TRUE),('ML_PRICE_AUTOMATION',TRUE),('ML_PROMOTION_ORCHESTRATOR',TRUE),('WEB_CROSS_SELL_DISCOUNTS',TRUE),('COMMERCIAL_CALENDAR',TRUE),('FAVORITES',TRUE),('LOYALTY',TRUE),('CARRIERS',TRUE),('ML_VIRTUAL_KITS',TRUE);
INSERT INTO capability_actions(module_code,action_code,allows_write) VALUES
 ('STOREFRONT','SERVE',FALSE),('CATALOG','MANAGE',TRUE),('PROFILE_CONTENT','MANAGE',TRUE),('PAYMENTS_MP','PROCESS_WEBHOOK',TRUE),('MANUAL_FULFILLMENT','MANAGE',TRUE),('MARKETPLACE_ML','SYNC',TRUE),('MANUAL_PROMOTIONS','WRITE_PRICE',TRUE),
 ('ML_COMPETITION_INSIGHTS','READ_SIGNALS',FALSE),('ML_PRICE_AUTOMATION','WRITE_PRICE',TRUE),('ML_PROMOTION_ORCHESTRATOR','PUBLISH_PROMOTION',TRUE),('WEB_CROSS_SELL_DISCOUNTS','APPLY_DISCOUNT',TRUE),('COMMERCIAL_CALENDAR','ACTIVATE_CAMPAIGN',TRUE),('FAVORITES','MANAGE',TRUE),('LOYALTY','POST_LEDGER',TRUE),('CARRIERS','SYNC',TRUE),('ML_VIRTUAL_KITS','MANAGE',TRUE);
INSERT INTO module_configurations(module_code,scope_kind,scope_key,state) SELECT module_code,'INSTALLATION','DEFAULT','DISABLED' FROM capability_modules;
CREATE FUNCTION enforce_future_optional_module_configuration() RETURNS TRIGGER LANGUAGE plpgsql AS $_$
BEGIN
 IF EXISTS (SELECT 1 FROM capability_modules WHERE module_code=NEW.module_code AND future_optional=TRUE) AND NEW.state <> 'DISABLED' THEN RAISE EXCEPTION 'future optional module % must remain DISABLED', NEW.module_code; END IF;
 RETURN NEW;
END;
$_$;
CREATE TRIGGER trg_enforce_future_optional_module_configuration BEFORE INSERT OR UPDATE OF module_code,state ON module_configurations FOR EACH ROW EXECUTE FUNCTION enforce_future_optional_module_configuration();
CREATE FUNCTION prevent_future_optional_activation() RETURNS TRIGGER LANGUAGE plpgsql AS $_$
BEGIN
 IF NEW.future_optional=TRUE AND EXISTS (SELECT 1 FROM module_configurations WHERE module_code=NEW.module_code AND state <> 'DISABLED') THEN RAISE EXCEPTION 'cannot mark active module % as future optional', NEW.module_code; END IF;
 RETURN NEW;
END;
$_$;
CREATE TRIGGER trg_prevent_future_optional_activation BEFORE UPDATE OF future_optional ON capability_modules FOR EACH ROW EXECUTE FUNCTION prevent_future_optional_activation();
CREATE TABLE universal_profile_imports (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, profile_name VARCHAR(120) NOT NULL, profile_version VARCHAR(32) NOT NULL,
 core_compatibility VARCHAR(64) NOT NULL, diff_snapshot JSONB NOT NULL, merge_selection JSONB NOT NULL, imported_by BIGINT NULL,
 imported_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(profile_name='universal-tools-profile'), CHECK(jsonb_typeof(diff_snapshot)='object'), CHECK(jsonb_typeof(merge_selection)='object')
);
CREATE TABLE roles (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, code VARCHAR(32) NOT NULL UNIQUE, description VARCHAR(160) NOT NULL, CHECK(code IN ('ADMIN','OPERATOR')));
CREATE TABLE users (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, email VARCHAR(320) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(email=lower(btrim(email)) AND password_hash LIKE '$2%'));
ALTER TABLE module_configurations ADD CONSTRAINT fk_module_configurations_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE RESTRICT;
CREATE TABLE user_roles (user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT, role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT, PRIMARY KEY(user_id,role_id));
CREATE TABLE customers (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, email VARCHAR(320) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(64) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(email=lower(btrim(email)) AND password_hash LIKE '$2%'));
CREATE TABLE customer_addresses (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT, street VARCHAR(160) NOT NULL, number VARCHAR(20) NOT NULL, city VARCHAR(100) NOT NULL, province VARCHAR(100) NOT NULL, postal_code VARCHAR(20) NOT NULL, is_default BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX uq_customer_default_address ON customer_addresses(customer_id) WHERE is_default;

CREATE TABLE brands (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(160) NOT NULL, slug VARCHAR(160) NOT NULL UNIQUE, description TEXT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(slug=lower(btrim(slug))));
CREATE TABLE categories (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, parent_id BIGINT NULL REFERENCES categories(id) ON DELETE RESTRICT, name VARCHAR(160) NOT NULL, slug VARCHAR(160) NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(slug=lower(btrim(slug)) AND sort_order>=0));
CREATE TABLE products (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, brand_id BIGINT NULL REFERENCES brands(id) ON DELETE RESTRICT, category_id BIGINT NULL REFERENCES categories(id) ON DELETE RESTRICT, name VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL UNIQUE, description TEXT NULL, base_price NUMERIC(14,2) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(base_price>=0 AND status IN ('DRAFT','ACTIVE','ARCHIVED')));
CREATE TABLE product_variants (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT, sku VARCHAR(128) NOT NULL UNIQUE, label VARCHAR(200) NOT NULL, attributes JSONB NOT NULL DEFAULT '{}'::jsonb, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(jsonb_typeof(attributes)='object'));
CREATE TABLE product_images (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT, url VARCHAR(2048) NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, is_primary BOOLEAN NOT NULL DEFAULT FALSE, CHECK(url ~ '^https://' AND sort_order>=0));
CREATE UNIQUE INDEX uq_product_primary_image ON product_images(product_id) WHERE is_primary;
CREATE TABLE home_content_sections (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, section_key VARCHAR(80) NOT NULL UNIQUE, content JSONB NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, updated_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(jsonb_typeof(content)='object' AND sort_order>=0));
CREATE TABLE offers (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(160) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'DRAFT', priority INTEGER NOT NULL DEFAULT 0, starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL, discount_type VARCHAR(16) NOT NULL, discount_value NUMERIC(14,2) NOT NULL, min_margin_percent NUMERIC(5,2) NOT NULL, created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT, approved_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT, approved_at TIMESTAMPTZ NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(status IN ('DRAFT','ACTIVE','PAUSED','ENDED') AND ends_at>starts_at AND discount_type IN ('PERCENT','FIXED') AND discount_value>0 AND min_margin_percent>=0), CHECK(status<>'ACTIVE' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)));
CREATE TABLE offer_products (offer_id BIGINT NOT NULL REFERENCES offers(id) ON DELETE RESTRICT, product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT, PRIMARY KEY(offer_id,product_id));

CREATE TABLE inventory_balances (variant_id BIGINT PRIMARY KEY REFERENCES product_variants(id) ON DELETE RESTRICT, available_quantity INTEGER NOT NULL DEFAULT 0, reserved_quantity INTEGER NOT NULL DEFAULT 0, safety_stock INTEGER NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(available_quantity>=0 AND reserved_quantity>=0 AND safety_stock>=0));
CREATE TABLE inventory_reservations (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT, reservation_saga_key UUID NOT NULL, reservation_line_key UUID NOT NULL UNIQUE, quantity INTEGER NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE', expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(quantity>0 AND status IN ('ACTIVE','CONSUMED','RELEASED','EXPIRED')), CHECK(expires_at>created_at), UNIQUE(reservation_saga_key,variant_id));
CREATE INDEX ix_active_inventory_reservation_expiry ON inventory_reservations(expires_at) WHERE status='ACTIVE';
CREATE TABLE inventory_ledger (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT, reservation_id BIGINT NULL REFERENCES inventory_reservations(id) ON DELETE RESTRICT, event_idempotency_key UUID NOT NULL UNIQUE, event_type VARCHAR(32) NOT NULL, channel VARCHAR(32) NOT NULL, external_order_id VARCHAR(128) NULL, external_order_item_id VARCHAR(128) NULL, variation_id VARCHAR(128) NULL, quantity_delta INTEGER NOT NULL, actor VARCHAR(100) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(event_type IN ('RESERVATION','RELEASE','SALE','REFUND','RETURN_RECEIVED','ADJUSTMENT','RECONCILIATION') AND channel IN ('WEB','MERCADO_LIBRE','INTERNAL') AND quantity_delta<>0));
CREATE INDEX ix_inventory_ledger_variant_created ON inventory_ledger(variant_id,created_at DESC);

CREATE TABLE carts (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT, session_id VARCHAR(128) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE cart_items (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE, variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT, quantity INTEGER NOT NULL, original_unit_price NUMERIC(14,2) NOT NULL, discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0, offer_id BIGINT NULL REFERENCES offers(id) ON DELETE RESTRICT, campaign_reference VARCHAR(160) NULL, effective_unit_price NUMERIC(14,2) NOT NULL, CHECK(quantity>0 AND original_unit_price>=0 AND discount_amount>=0 AND discount_amount<=original_unit_price AND effective_unit_price=original_unit_price-discount_amount), UNIQUE(cart_id,variant_id));
CREATE TABLE checkout_idempotency_claims (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT, checkout_idempotency_key UUID NOT NULL, request_hash CHAR(64) NOT NULL, checkout_snapshot JSONB NOT NULL, state VARCHAR(16) NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(customer_id,checkout_idempotency_key), UNIQUE(id,customer_id,checkout_idempotency_key,request_hash), CHECK(jsonb_typeof(checkout_snapshot)='object'), CHECK(state IN ('PENDING','COMPLETED','FAILED')));
CREATE TABLE orders (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, order_number VARCHAR(64) NOT NULL UNIQUE, checkout_claim_id BIGINT NOT NULL, checkout_idempotency_key UUID NOT NULL, checkout_request_hash CHAR(64) NOT NULL, customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT, status VARCHAR(32) NOT NULL DEFAULT 'CREATED', buyer_snapshot JSONB NOT NULL, checkout_snapshot JSONB NOT NULL, subtotal NUMERIC(14,2) NOT NULL, shipping_cost NUMERIC(14,2) NOT NULL DEFAULT 0,total NUMERIC(14,2) NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'ARS',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(checkout_claim_id),UNIQUE(customer_id,checkout_idempotency_key),FOREIGN KEY(checkout_claim_id,customer_id,checkout_idempotency_key,checkout_request_hash) REFERENCES checkout_idempotency_claims(id,customer_id,checkout_idempotency_key,request_hash) ON DELETE RESTRICT,CHECK(jsonb_typeof(buyer_snapshot)='object' AND jsonb_typeof(checkout_snapshot)='object' AND status IN ('CREATED','PENDING_PAYMENT','PAID','CANCELLED','EXPIRED','REFUNDED') AND subtotal>=0 AND shipping_cost>=0 AND total=subtotal+shipping_cost AND currency='ARS'));
CREATE TABLE order_items (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,offer_id BIGINT NULL REFERENCES offers(id) ON DELETE RESTRICT,campaign_reference VARCHAR(160) NULL,product_snapshot JSONB NOT NULL,quantity INTEGER NOT NULL,original_unit_price NUMERIC(14,2) NOT NULL,discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0,effective_unit_price NUMERIC(14,2) NOT NULL,subtotal NUMERIC(14,2) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(jsonb_typeof(product_snapshot)='object' AND quantity>0 AND original_unit_price>=0 AND discount_amount>=0 AND discount_amount<=original_unit_price AND effective_unit_price=original_unit_price-discount_amount AND subtotal=quantity*effective_unit_price));
CREATE TABLE payments (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT, provider VARCHAR(32) NOT NULL DEFAULT 'MERCADO_PAGO', external_reference VARCHAR(160) NOT NULL UNIQUE, provider_payment_id VARCHAR(128) NULL UNIQUE, status VARCHAR(32) NOT NULL DEFAULT 'PENDING', amount NUMERIC(14,2) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'ARS', raw_payload_redacted JSONB NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(provider='MERCADO_PAGO' AND status IN ('PENDING','APPROVED','REJECTED','CANCELLED','REFUNDED','CHARGED_BACK') AND amount>=0 AND currency='ARS'));
CREATE TABLE payment_event_inbox (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, provider VARCHAR(32) NOT NULL DEFAULT 'MERCADO_PAGO', provider_event_id VARCHAR(160) NOT NULL, resource_reference VARCHAR(256) NOT NULL, envelope_redacted JSONB NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(provider,provider_event_id), CHECK(provider='MERCADO_PAGO' AND jsonb_typeof(envelope_redacted) IN ('object','array')));
CREATE TABLE payment_event_processing (inbox_id BIGINT PRIMARY KEY REFERENCES payment_event_inbox(id) ON DELETE RESTRICT, status VARCHAR(16) NOT NULL DEFAULT 'RECEIVED', attempt_count INTEGER NOT NULL DEFAULT 0, lease_expires_at TIMESTAMPTZ NULL, locked_by VARCHAR(100) NULL, last_error VARCHAR(500) NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(status IN ('RECEIVED','PROCESSING','PROCESSED','FAILED') AND attempt_count>=0));
CREATE TABLE payment_event_applications (inbox_id BIGINT PRIMARY KEY REFERENCES payment_event_inbox(id) ON DELETE RESTRICT, payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE RESTRICT, resulting_status VARCHAR(32) NOT NULL, applied_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(resulting_status IN ('PENDING','APPROVED','REJECTED','CANCELLED','REFUNDED','CHARGED_BACK')));
CREATE TABLE integration_outbox (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, provider VARCHAR(32) NOT NULL, source_inbox_id BIGINT NOT NULL REFERENCES payment_event_inbox(id) ON DELETE RESTRICT, idempotency_key UUID NOT NULL UNIQUE, kind VARCHAR(64) NOT NULL, payload_redacted JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(provider,source_inbox_id,kind), CHECK(provider='MERCADO_PAGO' AND jsonb_typeof(payload_redacted) IN ('object','array')));
CREATE TABLE integration_outbox_delivery (outbox_id BIGINT PRIMARY KEY REFERENCES integration_outbox(id) ON DELETE RESTRICT, status VARCHAR(16) NOT NULL DEFAULT 'PENDING', attempt_count INTEGER NOT NULL DEFAULT 0, available_at TIMESTAMPTZ NOT NULL DEFAULT now(), lease_expires_at TIMESTAMPTZ NULL, locked_by VARCHAR(100) NULL, last_error VARCHAR(500) NULL, sent_at TIMESTAMPTZ NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(status IN ('PENDING','SENT','FAILED','DEAD') AND attempt_count>=0));
CREATE TABLE shipments (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,status VARCHAR(32) NOT NULL DEFAULT 'PENDING',tracking_code VARCHAR(128) NULL,shipped_at TIMESTAMPTZ NULL,delivered_at TIMESTAMPTZ NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK(status IN ('PENDING','PREPARING','SHIPPED','DELIVERED','CANCELLED')),CHECK((status IN ('PENDING','PREPARING','CANCELLED') AND shipped_at IS NULL AND delivered_at IS NULL) OR (status='SHIPPED' AND shipped_at IS NOT NULL AND delivered_at IS NULL) OR (status='DELIVERED' AND shipped_at IS NOT NULL AND delivered_at IS NOT NULL AND delivered_at>=shipped_at)));
CREATE TABLE fulfillment_events (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, shipment_id BIGINT NOT NULL REFERENCES shipments(id) ON DELETE RESTRICT, event_type VARCHAR(32) NOT NULL, occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(), actor VARCHAR(100) NOT NULL, details JSONB NOT NULL DEFAULT '{}'::jsonb, CHECK(jsonb_typeof(details)='object'));
CREATE TABLE returns (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, rma_number VARCHAR(64) NOT NULL UNIQUE, order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT, status VARCHAR(32) NOT NULL DEFAULT 'REQUESTED', received_at TIMESTAMPTZ NULL, inspection_result VARCHAR(32) NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(status IN ('REQUESTED','APPROVED','RETURN_RECEIVED','INSPECTED','REJECTED','CLOSED') AND (inspection_result IS NULL OR inspection_result IN ('RESTOCK','DAMAGED','REJECTED'))));
CREATE TABLE return_items (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, return_id BIGINT NOT NULL REFERENCES returns(id) ON DELETE RESTRICT, order_item_id BIGINT NOT NULL REFERENCES order_items(id) ON DELETE RESTRICT, quantity INTEGER NOT NULL, adjustment_ledger_id BIGINT NULL REFERENCES inventory_ledger(id) ON DELETE RESTRICT, CHECK(quantity>0));

CREATE TABLE channel_accounts (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, account_key VARCHAR(100) NOT NULL UNIQUE, channel VARCHAR(32) NOT NULL, oauth_secret_reference VARCHAR(255) NOT NULL, state VARCHAR(16) NOT NULL DEFAULT 'DISABLED', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(channel='MERCADO_LIBRE' AND state IN ('DISABLED','READ_ONLY','ACTIVE','PAUSED','ERROR')));
CREATE TABLE channel_listings (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, account_id BIGINT NOT NULL REFERENCES channel_accounts(id) ON DELETE RESTRICT, external_listing_id VARCHAR(128) NOT NULL, variation_id VARCHAR(128) NULL, variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT, desired_quantity INTEGER NOT NULL DEFAULT 0, observed_quantity INTEGER NULL, manual_intervention_required BOOLEAN NOT NULL DEFAULT FALSE, state VARCHAR(16) NOT NULL DEFAULT 'DISABLED', updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(desired_quantity>=0 AND (observed_quantity IS NULL OR observed_quantity>=0) AND state IN ('DISABLED','READ_ONLY','ACTIVE','PAUSED','ERROR')), UNIQUE NULLS NOT DISTINCT(account_id,external_listing_id,variation_id));
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TABLE channel_price_policies (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, listing_id BIGINT NOT NULL REFERENCES channel_listings(id) ON DELETE RESTRICT, currency CHAR(3) NOT NULL DEFAULT 'ARS', price_scope VARCHAR(16) NOT NULL DEFAULT 'DEFAULT', base_price NUMERIC(14,2) NOT NULL, desired_price NUMERIC(14,2) NOT NULL, observed_price NUMERIC(14,2) NULL, effective_promo_price NUMERIC(14,2) NULL, writer_kind VARCHAR(16) NOT NULL DEFAULT 'MANUAL', status VARCHAR(16) NOT NULL DEFAULT 'DRAFT', effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ NOT NULL, effective_window TSTZRANGE GENERATED ALWAYS AS (tstzrange(effective_from,effective_to,'[)')) STORED, approved_by BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT, approved_at TIMESTAMPTZ NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(currency='ARS' AND price_scope IN ('DEFAULT','CAMPAIGN') AND base_price>=0 AND desired_price>=0 AND (observed_price IS NULL OR observed_price>=0) AND (effective_promo_price IS NULL OR effective_promo_price>=0) AND writer_kind='MANUAL' AND status IN ('DRAFT','ACTIVE','PAUSED','ENDED') AND effective_to>effective_from), CHECK(status<>'ACTIVE' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)));
ALTER TABLE channel_price_policies ADD CONSTRAINT ex_active_price_policy_window EXCLUDE USING gist (listing_id WITH =, currency WITH =, price_scope WITH =, effective_window WITH &&) WHERE (status='ACTIVE');
CREATE TABLE ml_notification_inbox (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, account_id BIGINT NOT NULL REFERENCES channel_accounts(id) ON DELETE RESTRICT, notification_id VARCHAR(128) NOT NULL, topic VARCHAR(128) NOT NULL, resource VARCHAR(256) NOT NULL, payload_redacted JSONB NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(account_id,notification_id), CHECK(jsonb_typeof(payload_redacted) IN ('object','array')));
CREATE TABLE ml_notification_processing (inbox_id BIGINT PRIMARY KEY REFERENCES ml_notification_inbox(id) ON DELETE RESTRICT, status VARCHAR(16) NOT NULL DEFAULT 'RECEIVED', attempt_count INTEGER NOT NULL DEFAULT 0, lease_expires_at TIMESTAMPTZ NULL, locked_by VARCHAR(100) NULL, last_error VARCHAR(500) NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(status IN ('RECEIVED','PROCESSING','PROCESSED','FAILED') AND attempt_count>=0));
CREATE TABLE channel_sales (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, account_id BIGINT NOT NULL REFERENCES channel_accounts(id) ON DELETE RESTRICT, external_order_id VARCHAR(128) NOT NULL, external_order_item_id VARCHAR(128) NOT NULL, variation_id VARCHAR(128) NULL, variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT, ledger_entry_id BIGINT NOT NULL REFERENCES inventory_ledger(id) ON DELETE RESTRICT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE NULLS NOT DISTINCT(account_id,external_order_id,external_order_item_id,variation_id));
CREATE TABLE channel_outbox (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, idempotency_key UUID NOT NULL UNIQUE, account_id BIGINT NOT NULL REFERENCES channel_accounts(id) ON DELETE RESTRICT, listing_id BIGINT NULL REFERENCES channel_listings(id) ON DELETE RESTRICT, kind VARCHAR(32) NOT NULL, payload_redacted JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(jsonb_typeof(payload_redacted) IN ('object','array')));
CREATE TABLE channel_outbox_delivery (outbox_id BIGINT PRIMARY KEY REFERENCES channel_outbox(id) ON DELETE RESTRICT, status VARCHAR(16) NOT NULL DEFAULT 'PENDING', attempt_count INTEGER NOT NULL DEFAULT 0, available_at TIMESTAMPTZ NOT NULL DEFAULT now(), lease_expires_at TIMESTAMPTZ NULL, locked_by VARCHAR(100) NULL, last_error VARCHAR(500) NULL, sent_at TIMESTAMPTZ NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(status IN ('PENDING','SENT','FAILED','DEAD') AND attempt_count>=0));
CREATE TABLE reconciliation_runs (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, account_id BIGINT NOT NULL REFERENCES channel_accounts(id) ON DELETE RESTRICT, feed_cursor VARCHAR(256) NULL, observed_snapshot_hash CHAR(64) NULL, result VARCHAR(32) NOT NULL, manual_intervention_count INTEGER NOT NULL DEFAULT 0, started_at TIMESTAMPTZ NOT NULL DEFAULT now(), finished_at TIMESTAMPTZ NULL, CHECK(result IN ('RUNNING','COMPLETED','PARTIAL','FAILED') AND manual_intervention_count>=0));
CREATE TABLE audit_events (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor_type VARCHAR(32) NOT NULL, actor_id VARCHAR(128) NULL, event_type VARCHAR(128) NOT NULL, aggregate_type VARCHAR(64) NOT NULL, aggregate_id BIGINT NULL, payload_redacted JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(jsonb_typeof(payload_redacted) IN ('object','array')));
CREATE FUNCTION prevent_immutable_mutation() RETURNS TRIGGER LANGUAGE plpgsql AS $_$
BEGIN
 RAISE EXCEPTION '% is immutable; append a correction or update its processing/delivery projection', TG_TABLE_NAME;
 RETURN NULL;
END;
$_$;
CREATE FUNCTION prevent_order_snapshot_mutation() RETURNS TRIGGER LANGUAGE plpgsql AS $_$
BEGIN
 IF TG_OP='DELETE' OR OLD.buyer_snapshot IS DISTINCT FROM NEW.buyer_snapshot OR OLD.checkout_snapshot IS DISTINCT FROM NEW.checkout_snapshot OR OLD.checkout_claim_id IS DISTINCT FROM NEW.checkout_claim_id OR OLD.customer_id IS DISTINCT FROM NEW.customer_id OR OLD.checkout_idempotency_key IS DISTINCT FROM NEW.checkout_idempotency_key OR OLD.checkout_request_hash IS DISTINCT FROM NEW.checkout_request_hash THEN RAISE EXCEPTION 'order evidence is immutable'; END IF;
 RETURN NEW;
END;
$_$;
CREATE FUNCTION prevent_checkout_claim_evidence_mutation() RETURNS TRIGGER LANGUAGE plpgsql AS $_$
BEGIN
 IF TG_OP='DELETE' OR OLD.customer_id IS DISTINCT FROM NEW.customer_id OR OLD.checkout_idempotency_key IS DISTINCT FROM NEW.checkout_idempotency_key OR OLD.request_hash IS DISTINCT FROM NEW.request_hash OR OLD.checkout_snapshot IS DISTINCT FROM NEW.checkout_snapshot THEN RAISE EXCEPTION 'checkout claim evidence is immutable'; END IF;
 RETURN NEW;
END;
$_$;
CREATE TRIGGER trg_prevent_immutable_inventory_ledger BEFORE UPDATE OR DELETE ON inventory_ledger FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_immutable_payment_event_inbox BEFORE UPDATE OR DELETE ON payment_event_inbox FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_immutable_payment_event_applications BEFORE UPDATE OR DELETE ON payment_event_applications FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_immutable_integration_outbox BEFORE UPDATE OR DELETE ON integration_outbox FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_immutable_ml_notification_inbox BEFORE UPDATE OR DELETE ON ml_notification_inbox FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_immutable_channel_outbox BEFORE UPDATE OR DELETE ON channel_outbox FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_immutable_audit_events BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_immutable_universal_profile_imports BEFORE UPDATE OR DELETE ON universal_profile_imports FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_immutable_order_items BEFORE UPDATE OR DELETE ON order_items FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation();
CREATE TRIGGER trg_prevent_checkout_claim_evidence_mutation BEFORE UPDATE OR DELETE ON checkout_idempotency_claims FOR EACH ROW EXECUTE FUNCTION prevent_checkout_claim_evidence_mutation();
CREATE TRIGGER trg_prevent_order_snapshot_mutation BEFORE UPDATE OR DELETE ON orders FOR EACH ROW EXECUTE FUNCTION prevent_order_snapshot_mutation();
