import { CheckoutStep, DemoCommerce, DemoContext, DemoScenario, decodeSnapshot, demoSeed } from './demo-model';
import { PaymentStatus } from '../domain/order/payment-status';
import { ShipmentStatus } from '../domain/order/shipment-status';

describe('commercial demo transactions', () => {
  const commerce = () => new DemoCommerce(demoSeed(), () => '2026-10-08T10:00:00.000Z', () => 'fixed-request');
  it('closes unknown scenario, context and checkout values', () => { expect(DemoScenario.fromWire('invented')).toBe(DemoScenario.Unknown); expect(DemoContext.fromWire('root')).toBe(DemoContext.Unknown); expect(CheckoutStep.fromWire('skip-payment')).toBe(CheckoutStep.Unknown); });
  it('consumes once and returns the same receipt for the same request', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; const before = state.available(sku); state.add('cliente', sku, 2); const first = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Approved); const repeated = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Approved); expect(first).toBe(repeated); expect(state.available(sku)).toBe(before - 2); expect(state.snapshot.movements).toHaveLength(1); expect(state.actor('cliente').cart).toHaveLength(0); });
  it('reserves pending stock and releases rejected payment without duplicating', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; const product = state.product(sku); const before = product.onHand; state.add('cliente', sku, 3); const order = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Pending); expect(product.onHand).toBe(before); expect(product.reserved).toBe(3); state.resolvePayment(order.id, DemoScenario.Rejected); expect(product.reserved).toBe(0); expect(product.onHand).toBe(before); expect(() => state.resolvePayment(order.id, DemoScenario.Rejected)).toThrow(); });
  it('approves pending payment once and permits shipment afterward', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; state.add('cliente', sku, 1); const order = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Pending); expect(() => state.advance(order.id)).toThrow(); state.resolvePayment(order.id, DemoScenario.Approved); state.advance(order.id); expect(order.shipment).toBe(ShipmentStatus.Shipped); state.advance(order.id); expect(order.shipment).toBe(ShipmentStatus.Delivered); expect(() => state.advance(order.id)).toThrow(); });
  it('keeps a cart during recovery and isolates another actor', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; state.add('cliente', sku, 1); expect(() => state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Error)).toThrow(); expect(state.actor('cliente').cart).toHaveLength(1); expect(state.actor('cliente2').cart).toHaveLength(0); expect(() => state.add('cliente', sku, 999)).toThrow(); });
  it('rejected checkout does not change stock', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; const stock = state.available(sku); state.add('cliente', sku, 2); const order = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Rejected); expect(order.payment).toBe(PaymentStatus.Rejected); expect(state.available(sku)).toBe(stock); });
  it('deduplicates ML sale and forbids sale before simulated account connection', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; const stock = state.available(sku); expect(() => state.mlSale(sku, 'ml-1')).toThrow(); state.snapshot.mlConnected = true; state.mlSale(sku, 'ml-1'); state.mlSale(sku, 'ml-1'); expect(state.available(sku)).toBe(stock - 1); });
  it('rehydrates canonical states and refuses invalid stock snapshots', () => { const state = commerce(); const decoded = decodeSnapshot(JSON.stringify(state.snapshot)); expect(decoded.orders[0].payment).toBe(PaymentStatus.Approved); expect(decoded.orders[0].shipment).toBe(ShipmentStatus.Preparing); state.snapshot.products[0].reserved = 9999; expect(() => decodeSnapshot(JSON.stringify(state.snapshot))).toThrow(); });
  it('received return does not implicitly restock', () => { const state = commerce(); const order = state.snapshot.orders[2]; const stock = state.available(order.lines[0].sku); state.receiveReturn(order.id); expect(state.available(order.lines[0].sku)).toBe(stock); expect(() => state.receiveReturn(order.id)).toThrow(); });
  it('discounts are integer minor units and update when a campaign is paused', () => { const state = commerce(); const product = state.snapshot.products[0]; expect(state.price(product.sku)).toBe(Math.round(product.price * .9)); state.saveCampaign({ ...state.snapshot.campaigns[0], active: false }); expect(state.price(product.sku)).toBe(product.price); });
});
