import { DemoAccessIntent, DemoRecovery, DemoRecoveryPhase, validateDemoIdentity } from './demo-access';
import { DemoAdminFilter, DemoAdminSort } from './demo-admin-selection';
import { demoSeed, DemoContext } from './demo-model';

describe('demo access ownership and recovery',()=>{
 it('rejects arbitrary return URLs and only opens actor-owned orders',()=>{const data=demoSeed(); for(const wire of ['https://evil.invalid','//evil.invalid','/demo/checkout?redirect=evil','/demo/customer/orders/../user/home'])expect(DemoAccessIntent.fromWire(wire)).toBe(DemoAccessIntent.Unknown);const intent=DemoAccessIntent.fromWire('/demo/customer/orders/DEMO-102');expect(intent.destination(data,'cliente',DemoContext.Customer)).toBe('/demo');expect(intent.destination(data,'cliente2',DemoContext.Customer)).toBe('/demo/customer/orders/DEMO-102');expect(DemoAccessIntent.fromWire('/demo/user/orders').destination(data,'cliente',DemoContext.Customer)).toBe('/demo');});
 it('expires and consumes recovery once, with no credential changes',()=>{let now=1;const recovery=new DemoRecovery(()=>now);expect(recovery.inspect()).toBe(DemoRecoveryPhase.Unknown);expect(recovery.request()).toBe(DemoRecoveryPhase.Sent);expect(recovery.consume()).toBe(DemoRecoveryPhase.Completed);expect(recovery.consume()).toBe(DemoRecoveryPhase.Used);recovery.request();now+=300000;expect(recovery.consume()).toBe(DemoRecoveryPhase.Expired);expect(DemoRecoveryPhase.fromWire('garbage')).toBe(DemoRecoveryPhase.Unknown);});
 it('validates identity field boundaries and closed filters',()=>{expect(validateDemoIdentity('a@demo.invalid','Alex','Demo','011 5555')).toBe('');expect(validateDemoIdentity('bad','Alex','Demo')).toContain('Email');expect(validateDemoIdentity('a@demo.invalid','','Demo')).toContain('Nombre');expect(validateDemoIdentity('a@demo.invalid','A','D','script')).toContain('Teléfono');expect(DemoAdminFilter.fromWire('bad')).toBe(DemoAdminFilter.Unknown);expect(DemoAdminSort.fromWire('bad')).toBe(DemoAdminSort.Unknown);const p=demoSeed().products[0];expect(DemoAdminFilter.LowStock.product(p,1,5)).toBe(true);expect(DemoAdminFilter.LowStock.product({...p,active:false},1,5)).toBe(false);});
});
