import { CheckoutStep, DemoCommerce, DemoContext, DemoScenario, DemoProductVariant, DemoGalleryView, DemoModuleId, decodeSnapshot, demoSeed } from './demo-model';
import { PaymentStatus } from '../domain/order/payment-status';
import { ShipmentStatus } from '../domain/order/shipment-status';

describe('commercial demo transactions', () => {
  it('cart quantity edits reject invalid values without removal, only explicit remove deletes', () => { const state=new DemoCommerce(demoSeed()); state.add('cliente','DEMO-001',2); const before=JSON.stringify(state.snapshot); for(const invalid of [0,-1,-3,.5,1.5,Number.NaN]) { expect(()=>state.setQuantity('cliente','DEMO-001',invalid)).toThrow('cantidad entera'); expect(JSON.stringify(state.snapshot)).toBe(before); } state.setQuantity('cliente','DEMO-001',3); expect(state.actor('cliente').cart[0].quantity).toBe(3); state.remove('cliente','DEMO-001'); expect(state.actor('cliente').cart).toHaveLength(0); const revision=state.snapshot.revision; state.remove('cliente','DEMO-001'); expect(state.snapshot.revision).toBe(revision); });
  it('rejects zero, negative and fractional additions before changing either empty or existing carts', () => { const state=new DemoCommerce(demoSeed()); for(const initial of [0,2]) { if(initial) state.add('cliente','DEMO-001',initial); const before=JSON.stringify(state.snapshot); for(const invalid of [0,-1,-3,.5,1.5,Number.NaN]) { expect(()=>state.add('cliente','DEMO-001',invalid)).toThrow('cantidad entera'); expect(JSON.stringify(state.snapshot)).toBe(before); } } });
  it('rejects stale incompatible variants before cart mutation and fails closed on absent compatibility', () => { const state=new DemoCommerce(demoSeed()); const before=JSON.stringify(state.snapshot); expect(()=>state.add('cliente','DEMO-007',1,DemoProductVariant.Case)).toThrow('no está disponible'); expect(JSON.stringify(state.snapshot)).toBe(before); state.product('DEMO-001').supportsCase=undefined; const changed=JSON.stringify(state.snapshot); expect(()=>state.add('cliente','DEMO-001',1,DemoProductVariant.Case)).toThrow('no está disponible'); expect(JSON.stringify(state.snapshot)).toBe(changed); state.add('cliente','DEMO-007',1,DemoProductVariant.Standard); expect(state.actor('cliente').cart[0].variant).toBe(DemoProductVariant.Standard); });
  const commerce = () => new DemoCommerce(demoSeed(), () => '2026-10-08T10:00:00.000Z', () => 'fixed-request');
  it('closes unknown scenario, context and checkout values', () => { expect(DemoScenario.fromWire('invented')).toBe(DemoScenario.Unknown); expect(DemoContext.fromWire('root')).toBe(DemoContext.Unknown); expect(CheckoutStep.fromWire('skip-payment')).toBe(CheckoutStep.Unknown); });
  it('consumes once and returns the same receipt for the same request', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; const before = state.available(sku); state.add('cliente', sku, 2); const first = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Approved); const repeated = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Approved); expect(first).toBe(repeated); expect(state.available(sku)).toBe(before - 2); expect(state.snapshot.movements).toHaveLength(1); expect(state.actor('cliente').cart).toHaveLength(0); });
  it('reserves pending stock and releases rejected payment without duplicating', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; const product = state.product(sku); const before = product.onHand; state.add('cliente', sku, 3); const order = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Pending); expect(product.onHand).toBe(before); expect(product.reserved).toBe(3); state.resolvePayment(order.id, DemoScenario.Rejected); expect(product.reserved).toBe(0); expect(product.onHand).toBe(before); expect(() => state.resolvePayment(order.id, DemoScenario.Rejected)).toThrow(); });
  it('approves pending payment once and permits shipment afterward', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; state.add('cliente', sku, 1); const order = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Pending); expect(() => state.advance(order.id)).toThrow(); state.resolvePayment(order.id, DemoScenario.Approved); state.advance(order.id); expect(order.shipment).toBe(ShipmentStatus.Shipped); state.advance(order.id); expect(order.shipment).toBe(ShipmentStatus.Delivered); expect(() => state.advance(order.id)).toThrow(); });
  it('keeps a cart during recovery and isolates another actor', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; state.add('cliente', sku, 1); expect(() => state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Error)).toThrow(); expect(state.actor('cliente').cart).toHaveLength(1); expect(state.actor('cliente2').cart).toHaveLength(0); expect(() => state.add('cliente', sku, 999)).toThrow(); });
  it('rejected checkout does not change stock', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; const stock = state.available(sku); state.add('cliente', sku, 2); const order = state.checkout('cliente', 'request-1', 'address-cliente', DemoScenario.Rejected); expect(order.payment).toBe(PaymentStatus.Rejected); expect(state.available(sku)).toBe(stock); });
  it('deduplicates ML sale and forbids sale before simulated account connection', () => { const state = commerce(); const sku = state.snapshot.products[0].sku; const stock = state.available(sku); expect(() => state.mlSale(sku, 'ml-1')).toThrow(); state.snapshot.mlConnected = true; state.mlSale(sku, 'ml-1'); state.mlSale(sku, 'ml-1'); expect(state.available(sku)).toBe(stock - 1); });
  it('rehydrates canonical states and refuses invalid stock snapshots', () => { const state = commerce(); const decoded = decodeSnapshot(JSON.stringify(state.snapshot)); expect(decoded.orders[0].payment).toBe(PaymentStatus.Approved); expect(decoded.orders[0].shipment).toBe(ShipmentStatus.Preparing); state.snapshot.products[0].reserved = 9999; expect(() => decodeSnapshot(JSON.stringify(state.snapshot))).toThrow(); });
  it('received return does not implicitly restock', () => { const state = commerce(); const order = state.snapshot.orders[2]; const stock = state.available(order.lines[0].sku); state.receiveReturn(order.id); expect(state.available(order.lines[0].sku)).toBe(stock); expect(() => state.receiveReturn(order.id)).toThrow(); });
  it('discounts are integer minor units and update when a campaign is paused', () => { const state = commerce(); const product = state.snapshot.products[0]; expect(state.price(product.sku)).toBe(Math.round(product.price * .9)); state.saveCampaign({ ...state.snapshot.campaigns[0], active: false }); expect(state.price(product.sku)).toBe(product.price); });
  it('selected package changes quoted money, preserves SKU stock and rehydrates its closed type', () => { const state = commerce(); const sku = 'DEMO-001'; const before = state.available(sku); state.add('cliente',sku,2,DemoProductVariant.Case); const restored = decodeSnapshot(JSON.stringify(state.snapshot)); expect(restored.actors[0].cart[0].variant).toBe(DemoProductVariant.Case); const order=state.checkout('cliente','case-request','address-cliente',DemoScenario.Approved); expect(order.total).toBe(state.variantPrice(sku, `${sku}:with-case`)*2); expect(order.lines[0].name).toContain(DemoProductVariant.Case.label); expect(state.available(sku)).toBe(before-2); expect(DemoProductVariant.fromWire('invented')).toBe(DemoProductVariant.Unknown); expect(DemoGalleryView.fromWire('invented')).toBe(DemoGalleryView.Unknown); });
  it('paused checkout blocks new sales and configuration validates before updating', () => { const state=commerce(); state.snapshot.modules.find(module=>module.id===DemoModuleId.Checkout)!.enabled=false; state.add('cliente','DEMO-001',1); expect(()=>state.checkout('cliente','request','address-cliente',DemoScenario.Approved)).toThrow('pausado'); const before={...state.snapshot.settings}; expect(()=>state.saveSettings({...before,deliveryDays:0})).toThrow(); expect(state.snapshot.settings).toEqual(before); state.saveSettings({...before,deliveryDays:3}); expect(state.snapshot.settings.deliveryDays).toBe(3); expect(DemoModuleId.fromWire('invented')).toBe(DemoModuleId.Unknown); });
  it('rejects duplicate creation and preserves live reservations during edits', () => { const state=commerce(); state.add('cliente','DEMO-001',2); const order=state.checkout('cliente','pending-edit','address-cliente',DemoScenario.Pending); const product=state.product('DEMO-001'); expect(()=>state.saveProduct({...product,reserved:0})).toThrow('ya existe'); state.saveProduct({...product,name:'Editado',reserved:0},product.sku); expect(product.reserved).toBe(2); expect(()=>state.saveProduct({...product,onHand:1,reserved:0},product.sku)).toThrow('reservas'); state.resolvePayment(order.id,DemoScenario.Approved); expect(product.reserved).toBe(0); });
  it('rejects archived products already in cart without changing stock or orders', () => { const state=commerce(); state.add('cliente','DEMO-001',1); const product=state.product('DEMO-001'); state.saveProduct({...product,active:false},product.sku); const stock=product.onHand; const orders=state.snapshot.orders.length; expect(()=>state.checkout('cliente','archived','address-cliente',DemoScenario.Approved)).toThrow('archivado'); expect(product.onHand).toBe(stock); expect(state.snapshot.orders).toHaveLength(orders); state.remove('cliente',product.sku); expect(state.actor('cliente').cart).toHaveLength(0); });
});
