import { DemoCommerce, DemoScenario, decodeSnapshot, demoSeed } from './demo-model';
import { DemoDeliveryMethod, DemoPaymentMethod, DemoPaymentPhase, DemoMLTab, DemoSyncStatus } from './demo-process-types';
import { PaymentStatus } from '../domain/order/payment-status';
describe('commercial process snapshots and stock authority', () => {
  const create = () => new DemoCommerce(demoSeed(), () => '2026-10-09T12:00:00Z', () => 'purchase');
  it('all process borders close unknown values', () => { expect(DemoPaymentMethod.fromWire('other')).toBe(DemoPaymentMethod.Unknown); expect(DemoDeliveryMethod.fromWire('other')).toBe(DemoDeliveryMethod.Unknown); expect(DemoPaymentPhase.fromWire('other')).toBe(DemoPaymentPhase.Unknown); expect(DemoMLTab.fromWire('other')).toBe(DemoMLTab.Unknown); expect(DemoSyncStatus.fromWire('other')).toBe(DemoSyncStatus.Unknown); });
  it('pending and cancellation never consume or project a sale, cancellation is idempotent', () => { const commerce = create(); commerce.add('cliente','DEMO-001',2); const before = commerce.product('DEMO-001').onHand; const order = commerce.checkout('cliente','pending','address-cliente',DemoScenario.Pending,DemoPaymentMethod.Transfer,DemoDeliveryMethod.Home); expect(commerce.product('DEMO-001').onHand).toBe(before); expect(commerce.snapshot.syncJobs ?? []).toHaveLength(0); commerce.cancelPayment(order.id); commerce.cancelPayment(order.id); expect(commerce.product('DEMO-001').reserved).toBe(0); expect(commerce.product('DEMO-001').onHand).toBe(before); expect(commerce.snapshot.movements).toHaveLength(0); expect(order.payment).toBe(PaymentStatus.Cancelled); });
  it('order snapshots freeze delivery price and address and rehydrate closed method', () => { const commerce = create(); commerce.add('cliente','DEMO-001',1); const order = commerce.checkout('cliente','paid','address-cliente',DemoScenario.Approved,DemoPaymentMethod.QR,DemoDeliveryMethod.Home); commerce.actor('cliente').addresses[0].street='Different'; commerce.snapshot.settings.deliveryDays=20; expect(order.delivery?.destination).toContain('Avenida de muestra 123'); expect(order.delivery?.days).toBe(5); expect(order.total).toBe(commerce.price('DEMO-001') + DemoDeliveryMethod.Home.cost); const restored=decodeSnapshot(JSON.stringify(commerce.snapshot)); expect(restored.orders.at(-1)?.method).toBe(DemoPaymentMethod.QR); expect(restored.orders.at(-1)?.delivery?.method).toBe(DemoDeliveryMethod.Home); });
  it('queues approved stock, provider confirms separately and sales dedupe', () => { const commerce = create(); commerce.snapshot.mlConnected=true; commerce.add('cliente','DEMO-001',1); commerce.checkout('cliente','paid','address-cliente',DemoScenario.Approved); const listing=commerce.snapshot.listings[0]; expect(listing.observed).toBe(18); expect(listing.desired).toBe(17); commerce.processStock(true); expect(commerce.snapshot.syncJobs?.[0].status).toBe(DemoSyncStatus.Failed); commerce.processStock(); expect(listing.confirmed).toBe(17); const jobs=commerce.snapshot.syncJobs!.length; commerce.processStock(); expect(commerce.snapshot.syncJobs).toHaveLength(jobs); commerce.mlSale('DEMO-001','event-1'); commerce.mlSale('DEMO-001','event-1'); expect(commerce.product('DEMO-001').onHand).toBe(16); });
  it('pickup has no address dependency and no fee', () => { const commerce=create(); commerce.actor('cliente').addresses=[]; commerce.add('cliente','DEMO-001',1); const order=commerce.checkout('cliente','pickup','',DemoScenario.Approved,DemoPaymentMethod.Card,DemoDeliveryMethod.Pickup); expect(order.delivery?.destination).toContain('Retiro'); expect(order.total).toBe(commerce.price('DEMO-001')); });
  it('watchlist alert threshold and pause are effective', () => { const commerce=create(); commerce.watchCompetitor('Demo competitor','DEMO-001',10); const competitor=commerce.snapshot.competitors.at(-1)!; commerce.competitorPrice(competitor.id, competitor.price-100); expect(competitor.unread).toBe(false); commerce.competitorPrice(competitor.id,competitor.price/2|0); expect(competitor.unread).toBe(true); competitor.unread=false; competitor.enabled=false; commerce.competitorPrice(competitor.id,competitor.price*2); expect(competitor.unread).toBe(false); });
});
