import { DemoCommerce, demoSeed, DemoScenario, decodeSnapshot } from './demo-model';
import { DemoReturnReason, DemoReturnStatus, DemoReturnDisposition, DemoReturnPolicy, DemoRefundAllocation } from './demo-postsale';
import { ShipmentStatus } from '../domain/order/shipment-status';

describe('partial post-sale lifecycle', () => {
  function sale() { let id = 0; const commerce = new DemoCommerce(demoSeed(), () => '2026-10-09T15:00:00Z', () => `operation-${++id}`); commerce.add('cliente', 'DEMO-001', 3); commerce.add('cliente', 'DEMO-002', 2); const order = commerce.checkout('cliente', 'sale', 'address-cliente', DemoScenario.Approved); commerce.advance(order.id); commerce.advance(order.id); return { commerce, order }; }
  it('per line partial quantities retain paid discounted snapshots and refuse foreign ownership', () => { const { commerce, order } = sale(); const line = order.lines[0]; expect(() => commerce.requestReturn('cliente2', order.id, 'r1', [{ variantId: line.variantId!, quantity: 1, reason: DemoReturnReason.Damaged }])).toThrow('propio'); commerce.product(line.sku).variants![0].price += 100; const request = commerce.requestReturn('cliente', order.id, 'r1', [{ variantId: line.variantId!, quantity: 2, reason: DemoReturnReason.Damaged }]); expect(request.lines[0].refund).toBe(line.unit * 2); expect(new DemoReturnPolicy().available(order, line.variantId!)).toBe(1); expect(request.lines[0].name).toBe(line.name); });
  it('checks all requested lines before any mutation and rejects Unknown and invalid quantities', () => { const { commerce, order } = sale(); const before = JSON.stringify(commerce.snapshot); for (const quantity of [0, -1, .5, 4, NaN]) expect(() => commerce.requestReturn('cliente', order.id, 'invalid', [{ variantId: order.lines[0].variantId!, quantity, reason: DemoReturnReason.Damaged }])).toThrow(); expect(() => commerce.requestReturn('cliente', order.id, 'unknown', [{ variantId: order.lines[0].variantId!, quantity: 1, reason: DemoReturnReason.Unknown }])).toThrow(); expect(JSON.stringify(commerce.snapshot)).toBe(before); });
  it('decision rejects with reason and releases the selected quantity for a new request', () => { const { commerce, order } = sale(); const selection = [{ variantId: order.lines[0].variantId!, quantity: 3, reason: DemoReturnReason.ChangedMind }]; const request = commerce.requestReturn('cliente', order.id, 'r1', selection); expect(() => commerce.decideReturn(order.id, request.id, false, '')).toThrow(); commerce.decideReturn(order.id, request.id, false, 'Fuera de la política de devolución'); expect(request.status).toBe(DemoReturnStatus.Rejected); expect(new DemoReturnPolicy().available(order, selection[0].variantId)).toBe(3); expect(commerce.requestReturn('cliente', order.id, 'r2', selection).status).toBe(DemoReturnStatus.Requested); });
  it('restocks once only inspected sellable lines and records refund once without stock changes', () => { const { commerce, order } = sale(); const selections = order.lines.map(line => ({ variantId: line.variantId!, quantity: 1, reason: DemoReturnReason.Defective })); const request = commerce.requestReturn('cliente', order.id, 'r1', selections); const stocks = order.lines.map(line => commerce.variantAvailable(line.sku, line.variantId!)); expect(() => commerce.refundReturn(order.id, request.id)).toThrow(); commerce.decideReturn(order.id, request.id, true, 'Aprobada para revisión'); expect(() => commerce.inspectReturn(order.id, request.id, [{ variantId: selections[0].variantId, disposition: DemoReturnDisposition.Sellable }])).toThrow(); const outcomes = [{ variantId: selections[0].variantId, disposition: DemoReturnDisposition.Sellable }, { variantId: selections[1].variantId, disposition: DemoReturnDisposition.Quarantine }]; commerce.inspectReturn(order.id, request.id, outcomes); const revision = commerce.snapshot.revision; commerce.inspectReturn(order.id, request.id, outcomes); expect(commerce.snapshot.revision).toBe(revision); expect(order.lines.map(line => commerce.variantAvailable(line.sku, line.variantId!))).toEqual([stocks[0] + 1, stocks[1]]); commerce.refundReturn(order.id, request.id); const after = JSON.stringify(commerce.snapshot); commerce.refundReturn(order.id, request.id); expect(JSON.stringify(commerce.snapshot)).toBe(after); expect(request.refundId).toContain('SIM-REFUND'); expect(new DemoReturnPolicy().refunded(order)).toBe(request.lines.reduce((sum, line) => sum + line.refund, 0)); expect(commerce.snapshot.postSaleAlerts).toHaveLength(4); });
  it('deduplicates identical commands and rejects changed payloads on reuse', () => { const { commerce, order } = sale(); const selections = [{ variantId: order.lines[0].variantId!, quantity: 1, reason: DemoReturnReason.Damaged }]; const first = commerce.requestReturn('cliente', order.id, 'same', selections); const before = JSON.stringify(commerce.snapshot); expect(commerce.requestReturn('cliente', order.id, 'same', selections)).toBe(first); expect(JSON.stringify(commerce.snapshot)).toBe(before); expect(() => commerce.requestReturn('cliente', order.id, 'same', [{ ...selections[0], quantity: 2 }])).toThrow('otros datos'); });
  it('allocates every cent stably across split partial returns', () => { const allocation = new DemoRefundAllocation(); expect([0, 1, 2].map(prior => allocation.amount(100, 3, prior, 1))).toEqual([34, 33, 33]); expect(allocation.amount(100, 3, 0, 2) + allocation.amount(100, 3, 2, 1)).toBe(100); });
  it('multiple refunds exhaust bought quantities and preserve every paid discounted cent', () => { const { commerce, order } = sale(); const line = order.lines[0]; for (const quantity of [2, 1]) { const request = commerce.requestReturn('cliente', order.id, `partial-${quantity}`, [{ variantId: line.variantId!, quantity, reason: DemoReturnReason.ChangedMind }]); commerce.decideReturn(order.id, request.id, true, 'Devolución aprobada'); commerce.inspectReturn(order.id, request.id, [{ variantId: line.variantId!, disposition: DemoReturnDisposition.Sellable }]); commerce.refundReturn(order.id, request.id); } expect(new DemoReturnPolicy().available(order, line.variantId!)).toBe(0); expect(new DemoReturnPolicy().refunded(order)).toBe(line.unit * 3); expect(() => commerce.requestReturn('cliente', order.id, 'excess', [{ variantId: line.variantId!, quantity: 1, reason: DemoReturnReason.Damaged }])).toThrow(); expect(decodeSnapshot(JSON.stringify(commerce.snapshot)).orders.at(-1)!.returns).toHaveLength(2); });
  it('unknown reason on a persisted request blocks all administrative commands', () => { const { commerce, order } = sale(); const request = commerce.requestReturn('cliente', order.id, 'r1', [{ variantId: order.lines[0].variantId!, quantity: 1, reason: DemoReturnReason.Damaged }]); request.lines[0].reason = DemoReturnReason.Unknown; const restored = new DemoCommerce(decodeSnapshot(JSON.stringify(commerce.snapshot))); expect(() => restored.decideReturn(order.id, request.id, true, 'No')).toThrow('no disponible'); });
  it('v3 rehydrates and validates quantities/money, while v2 received legacy fails closed', () => { const { commerce, order } = sale(); const request = commerce.requestReturn('cliente', order.id, 'r1', [{ variantId: order.lines[0].variantId!, quantity: 2, reason: DemoReturnReason.Damaged }]); const restored = decodeSnapshot(JSON.stringify(commerce.snapshot)); expect(restored.version).toBe(3); expect(restored.orders.at(-1)!.returns![0].status).toBe(DemoReturnStatus.Requested); expect(restored.orders.at(-1)!.returns![0].lines[0].reason).toBe(DemoReturnReason.Damaged); request.lines[0].refund++; expect(() => decodeSnapshot(JSON.stringify(commerce.snapshot))).toThrow('dinero'); const legacy = demoSeed(); legacy.version = 2; legacy.orders[2].returned = true; const migrated = decodeSnapshot(JSON.stringify(legacy)); expect(migrated.orders[2].returns![0].status).toBe(DemoReturnStatus.Legacy); const legacyCommerce = new DemoCommerce(migrated); expect(() => legacyCommerce.requestReturn('cliente2', legacy.orders[2].id, 'new', [{ variantId: legacy.orders[2].lines[0].variantId!, quantity: 1, reason: DemoReturnReason.Damaged }])).toThrow(); });
  it('unknown persisted states are non-operable; un-delivered orders cannot request', () => { expect(DemoReturnStatus.fromWire('invented')).toBe(DemoReturnStatus.Unknown); expect(DemoReturnReason.fromWire('invented')).toBe(DemoReturnReason.Unknown); expect(DemoReturnDisposition.fromWire('invented')).toBe(DemoReturnDisposition.Unknown); const { commerce, order } = sale(); order.shipment = ShipmentStatus.Shipped; expect(() => commerce.requestReturn('cliente', order.id, 'r1', [{ variantId: order.lines[0].variantId!, quantity: 1, reason: DemoReturnReason.Damaged }])).toThrow('entregado'); });
});
