import { DemoCommerce, decodeSnapshot, demoSeed, DemoScenario } from './demo-model';
import { DemoMLAccountStatus, DemoMappingStatus, DemoObservationStatus, DemoMarketplaceMapping, DemoMarketplaceProcessor, DemoMarketplaceProjection, competitorFreshness, ensureCompetitorDetails, ensureMarketplace } from './demo-marketplace';
import { DemoSyncStatus } from './demo-process-types';
import { DemoInboxPolicy, DemoAlertRead, DemoAlertResolution } from './demo-inbox';

const now = '2026-10-09T10:00:00.000Z';
const setup = () => new DemoCommerce(demoSeed(), () => now, () => 'operation-fixed');
describe('FE-COMP-06 marketplace simulator invariants', () => {
  it('closes unknown wire values and rehydrates only canonical cases', () => { expect(DemoMLAccountStatus.fromWire('live')).toBe(DemoMLAccountStatus.Unknown); expect(DemoMappingStatus.fromWire('magic')).toBe(DemoMappingStatus.Unknown); expect(DemoObservationStatus.fromWire('scraped')).toBe(DemoObservationStatus.Unknown); const commerce = setup(); commerce.setMLAccount(DemoMLAccountStatus.Paused); const state = decodeSnapshot(JSON.stringify(commerce.snapshot)); expect(state.version).toBe(5); expect(state.marketplace!.account).toBe(DemoMLAccountStatus.Paused); expect(state.marketplace!.mappings[0].status).toBe(DemoMappingStatus.Linked); });
  it('migrates v4 legacy listings into explicit variant identities without inventing observed or confirmed stock', () => { const seed = demoSeed(); const decoded = decodeSnapshot(JSON.stringify(seed)); const mapping = decoded.marketplace!.mappings[0]; expect(mapping.variantId).toBe(seed.products[0].variants![0].id); expect(mapping.listingId).toBe('SIM-DEMO-001'); expect(mapping.observed).toBeUndefined(); expect(mapping.confirmed).toBeUndefined(); expect(decoded.marketplace!.account).toBe(DemoMLAccountStatus.Disconnected); });
  it('rejects corrupt v5 instead of silently migrating it', () => { const seed = demoSeed(); seed.version = 5; expect(() => decodeSnapshot(JSON.stringify(seed))).toThrow('Falta el canal'); const commerce = setup(); commerce.setMLAccount(DemoMLAccountStatus.Authorized); commerce.snapshot.marketplace!.mappings[0].desired = -1; expect(() => decodeSnapshot(JSON.stringify(commerce.snapshot))).toThrow('Mapping'); });
  it('retains debt through pause, expired and error, then converges exactly once', () => { const commerce = setup(); commerce.setMLAccount(DemoMLAccountStatus.Authorized); commerce.processStock(); const mapping = commerce.snapshot.marketplace!.mappings[0]; const originalConfirmed = mapping.confirmed; for (const state of [DemoMLAccountStatus.Paused, DemoMLAccountStatus.Expired, DemoMLAccountStatus.Error]) { commerce.setMLAccount(state); commerce.adjust(mapping.sku, 1, 'Ingreso', mapping.variantId); expect(mapping.confirmed).toBe(originalConfirmed); expect(() => commerce.processStock()).toThrow('deuda'); } commerce.setMLAccount(DemoMLAccountStatus.Authorized); commerce.processStock(true); expect(mapping.confirmed).toBe(originalConfirmed); expect(commerce.snapshot.marketplace!.queue.some(value => value.status === DemoSyncStatus.Failed)).toBe(true); commerce.processStock(); expect(mapping.confirmed).toBe(mapping.local); const queue = JSON.stringify(commerce.snapshot.marketplace!.queue); commerce.processStock(); expect(JSON.stringify(commerce.snapshot.marketplace!.queue)).toBe(queue); });
  it('maps by variant identity and blocks duplicate provider targets atomically', () => { const commerce = setup(); const other = commerce.variants('DEMO-001')[1]; const mapping = ensureMarketplace(commerce.snapshot).mappings[0]; const before = JSON.stringify(commerce.snapshot); expect(() => commerce.mapML('DEMO-001', other.id, mapping.listingId, mapping.variationId)).toThrow('Conflicto'); expect(JSON.stringify(commerce.snapshot)).toBe(before); commerce.mapML('DEMO-001', other.id, mapping.listingId, 'SIM-distinct-variation'); commerce.setMLAccount(DemoMLAccountStatus.Authorized); const original = commerce.variantAvailable('DEMO-001', other.id); commerce.mlSale('DEMO-001', 'sale-variant', other.id); commerce.mlSale('DEMO-001', 'sale-variant', other.id); expect(commerce.variantAvailable('DEMO-001', other.id)).toBe(original - 1); expect(commerce.snapshot.movements.filter(value => value.id === 'sale-variant')).toHaveLength(1); });
  it('blocks stock underflow and a sale operation reused for another variant', () => { const commerce = setup(); commerce.setMLAccount(DemoMLAccountStatus.Authorized); commerce.mlSale('DEMO-001', 'sale'); expect(() => commerce.mlSale('DEMO-002', 'sale')).toThrow('otra variante'); const mapping = commerce.snapshot.marketplace!.mappings[0]; commerce.adjust(mapping.sku, -commerce.variantAvailable(mapping.sku, mapping.variantId), 'Agotado', mapping.variantId); expect(() => commerce.mlSale(mapping.sku, 'another')).toThrow('sin stock'); });
  it('reserves web stock into desired, supersedes old generations and preserves observed', () => { const commerce = setup(); commerce.setMLAccount(DemoMLAccountStatus.Authorized); commerce.processStock(); const mapping = commerce.snapshot.marketplace!.mappings[0]; const observed = mapping.observed; commerce.add('cliente', mapping.sku, 2); commerce.checkout('cliente', 'pending-reserve', 'address-cliente', DemoScenario.Pending); expect(mapping.local).toBe(observed! - 2); expect(mapping.desired).toBe(mapping.local); expect(mapping.observed).toBe(observed); commerce.cancelPayment(commerce.snapshot.orders.at(-1)!.id); expect(mapping.local).toBe(observed); expect(commerce.snapshot.marketplace!.queue.some(value => value.status === DemoSyncStatus.Superseded)).toBe(true); });
  it('detects persisted conflicts and excludes them from processing', () => { const commerce = setup(); commerce.setMLAccount(DemoMLAccountStatus.Authorized); const state = commerce.snapshot; state.marketplace!.mappings[1].listingId = state.marketplace!.mappings[0].listingId; state.marketplace!.mappings[1].variationId = state.marketplace!.mappings[0].variationId; const decoded = decodeSnapshot(JSON.stringify(state)); expect(decoded.marketplace!.mappings[0].status).toBe(DemoMappingStatus.Conflict); new DemoMarketplaceProcessor().process(decoded, now); expect(decoded.marketplace!.mappings[0].confirmed).toBeUndefined(); });
  it('unlinks a mapping without losing history and remaps with new generation', () => { const commerce = setup(); commerce.setMLAccount(DemoMLAccountStatus.Authorized); const mapping = commerce.snapshot.marketplace!.mappings[0]; commerce.unlinkML(mapping.id); expect(mapping.status).toBe(DemoMappingStatus.Unlinked); expect(() => commerce.mlSale(mapping.sku, 'unlinked')).toThrow(); new DemoMarketplaceMapping().save(commerce.snapshot, mapping.sku, mapping.variantId, 'SIM-remapped', 'SIM-new', now); expect(mapping.generation).toBe(1); new DemoMarketplaceProjection().refresh(commerce.snapshot, now); expect(commerce.snapshot.marketplace!.queue.filter(value => value.mappingId === mapping.id && value.status === DemoSyncStatus.Queued)).toHaveLength(1); });
  it('dates competitor observations and deduplicates alerts without changing own prices', () => { const commerce = setup(); const competitor = commerce.snapshot.competitors[0]; const own = commerce.product('DEMO-001').price; commerce.competitorPrice(competitor.id, competitor.price - 50000, 'price-event'); const length = competitor.history.length; commerce.competitorPrice(competitor.id, competitor.price, 'price-event'); expect(competitor.history).toHaveLength(length); expect(competitor.details!.signals).toHaveLength(1); expect(commerce.product('DEMO-001').price).toBe(own); expect(competitorFreshness(competitor, commerce.snapshot, '2026-10-11T10:00:00Z')).toBe(DemoObservationStatus.Stale); competitor.details!.availability = DemoObservationStatus.Unavailable; expect(competitorFreshness(competitor, commerce.snapshot, now)).toBe(DemoObservationStatus.Unavailable); });
  it('reading an alert does not resolve its commercial signal or create duplicate inbox alerts', () => { const commerce = setup(); const competitor = commerce.snapshot.competitors[0]; commerce.competitorPrice(competitor.id, competitor.price - 50000, 'price-event'); const inbox = new DemoInboxPolicy(); inbox.reconcile(commerce.snapshot, now); const alert = commerce.snapshot.inbox!.alerts.find(value => value.id.includes('price-event'))!; inbox.mark(commerce.snapshot, 'admin', alert.id, DemoAlertRead.Read); inbox.reconcile(commerce.snapshot, now); expect(alert.resolution).toBe(DemoAlertResolution.Active); expect(alert.read).toBe(DemoAlertRead.Read); expect(commerce.snapshot.inbox!.alerts.filter(value => value.id === alert.id)).toHaveLength(1); });
  it('respects threshold, paused alerts and explicit price replay conflict', () => { const commerce = setup(); const competitor = commerce.snapshot.competitors[0]; competitor.threshold = 100; commerce.competitorPrice(competitor.id, competitor.price - 100, 'small'); expect(ensureCompetitorDetails(competitor, commerce.snapshot).signals).toHaveLength(0); competitor.enabled = false; competitor.threshold = 1; commerce.competitorPrice(competitor.id, competitor.price - 50000, 'disabled'); expect(competitor.details!.signals).toHaveLength(0); expect(() => commerce.competitorPrice(competitor.id, competitor.price + 100, 'disabled')).toThrow('otro precio'); });
});
