import { test, expect, Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const cta=(page:Page,id:string)=>page.locator(`[data-cta="${id}"]`);
async function login(page:Page,admin=false,email='cliente@demo.invalid'){await page.goto('/demo/login');await page.getByLabel('Perfil comprador de muestra').selectOption(email);await page.getByLabel('Contraseña',{exact:true}).fill('demo');await cta(page,'login-submit').click();await cta(page,admin?'login-admin':'login-customer').click();}
test('C05 explicit profiles, safe intent and customer ownership',async({page})=>{
 await page.goto('/demo/customer/orders/DEMO-102');await cta(page,'access-login').click();await page.getByLabel('Contraseña',{exact:true}).fill('incorrect');await cta(page,'login-submit').click();await expect(page.getByRole('alert')).toContainText('Código');await expect(cta(page,'login-customer')).not.toBeVisible();await page.getByLabel('Perfil comprador de muestra').selectOption('cliente2@demo.invalid');await page.getByLabel('Contraseña',{exact:true}).fill('demo');await cta(page,'login-submit').click();await cta(page,'login-customer').click();await expect(page).toHaveURL(/orders\/DEMO-102$/);await page.reload();await expect(page.locator('main')).toContainText('DEMO-102');await cta(page,'shell-logout').click();await login(page);await page.goto('/demo/customer/orders/DEMO-102');await expect(page.getByRole('heading',{name:'Pedido no disponible'})).toBeVisible();await page.goto('/demo/cart');await expect(page.locator('main')).toContainText('Tu carrito espera');
});
test('C05 neutral recovery expires and refuses reused links',async({page})=>{
 await page.goto('/demo/login');await cta(page,'login-recovery').click();await page.getByLabel('Email de muestra').fill('unknown@demo.invalid');await cta(page,'recovery-request').click();await expect(page.locator('main')).toContainText('Si existe un perfil');await cta(page,'recovery-expire').click();await expect(page.locator('main')).toContainText('Enlace vencido');await cta(page,'recovery-again').click();await cta(page,'recovery-request').click();await cta(page,'recovery-open').click();await cta(page,'recovery-complete').click();await cta(page,'recovery-reuse').click();await expect(page.locator('main')).toContainText('Enlace ya utilizado');await cta(page,'recovery-login').click();await expect(cta(page,'login-submit')).toBeVisible();
});
test('C05 duplicate registration and admin selections preserve saved state',async({page})=>{
 await page.goto('/demo/customer/register');await page.getByLabel('Nombre',{exact:true}).fill('Alex');await page.getByLabel('Apellido',{exact:true}).fill('Demo');await page.getByLabel('Email',{exact:true}).fill(' CLIENTE@demo.invalid ');await page.getByLabel('Contraseña',{exact:true}).fill('demo');await cta(page,'login-submit').click();await expect(page.getByRole('alert')).toContainText('ya existe');await expect(page.getByRole('alert')).toBeFocused();await login(page,true);await page.goto('/demo/user/catalog');await cta(page,'admin-filter').selectOption('archived');await expect(page.locator('table')).toContainText('No hay productos');await cta(page,'admin-filter').selectOption('active');await cta(page,'admin-sort').selectOption('name');await expect(page.locator('tbody tr')).toHaveCount(12);await page.getByLabel('Buscar',{exact:true}).fill('NO-MATCH');await expect(page.locator('table')).toContainText('No hay productos');await page.goto('/demo/user/offers');await cta(page,'admin-filter').selectOption('archived');await expect(page.locator('main')).toContainText('No hay promociones');await page.goto('/demo/user/content');await page.getByLabel('Título principal').fill('Borrador descartado');await cta(page,'content-cancel').click();await expect(page.getByLabel('Título principal')).not.toHaveValue('Borrador descartado');await page.getByLabel('Título principal').fill('Portada guardada C05');await cta(page,'content-save').click();await page.reload();await expect(page.getByLabel('Título principal')).toHaveValue('Portada guardada C05');
});
test('C05 paginated administration exposes every matching product',async({page})=>{
 await page.goto('/demo');await cta(page,'shell-reset-open').click();await cta(page,'shell-reset-confirm').click();await login(page,true);await page.evaluate(()=>{const key='storecore.commercial-demo.v1';const raw=localStorage.getItem(key);if(!raw)throw new Error('Missing demo state');const data=JSON.parse(raw);const original=data.products[0];for(let i=0;i<25;i++){const product=structuredClone(original);product.sku=`PAGING-${i}`;product.name=`Producto de paginación ${i}`;product.variants=product.variants.map((variant:{id:string},index:number)=>({...variant,id:`PAGING-${i}:${index}`}));data.products.push(product);}data.revision++;localStorage.setItem(key,JSON.stringify(data));});await page.goto('/demo/user/catalog');await expect(page.locator('tbody tr')).toHaveCount(20);await cta(page,'admin-page-next').click();await expect(page.locator('tbody tr')).toHaveCount(17);await cta(page,'admin-page-prev').click();await expect(page.locator('tbody tr')).toHaveCount(20);await page.getByLabel('Buscar',{exact:true}).fill('PAGING-24');await expect(page.locator('tbody tr')).toHaveCount(1);
});
for(const width of [390,768,1440])test(`C05 access keyboard and accessibility ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:900});await page.goto('/demo/login');await page.getByLabel('Contraseña',{exact:true}).fill('demo');await cta(page,'login-submit').focus();await page.keyboard.press('Enter');await expect(cta(page,'login-customer')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.screenshot({path:info.outputPath('access.png'),fullPage:true});await cta(page,'login-admin').click();await page.goto('/demo/user/catalog');expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
});
