import { expect, Page, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { DemoScreen } from '../src/app/demo/demo-screen';
const cta = (page: Page, id: string) => page.locator(`[data-cta="${id}"]`);

for (const delivery of [{ method: 'home', fee: '3.500', total: '14.750', width: 390 }, { method: 'pickup', fee: '0', total: '11.250', width: 1440 }]) {
 test(`cart delivery quote ${delivery.method} agrees with checkout and receipt`, async({page},testInfo)=>{
  await page.setViewportSize({width:delivery.width,height:900}); await login(page); await page.goto('/demo/catalog/DEMO-001'); await cta(page,'product-add-cart').click(); await cta(page,'product-review-cart').click(); await expect(page.locator('.summary')).toContainText('Subtotal de productos'); await expect(page.locator('.summary')).toContainText('A calcular en checkout'); await expect(page.locator('.summary')).not.toContainText('Sin cargo'); await expect(page.locator('.summary .total')).toContainText('11.250'); await page.screenshot({path:testInfo.outputPath(`cart-subtotal-${delivery.width}.png`),fullPage:true});
  await cta(page,'cart-checkout').click(); await page.getByRole('radio').check(); await cta(page,'checkout-step-next').click(); await cta(page,'checkout-delivery-method').selectOption(delivery.method); await cta(page,'checkout-step-next').click(); await expect(page.locator('.summary .total')).toContainText(delivery.total); await expect(cta(page,'checkout-confirm')).toContainText(delivery.total); await page.screenshot({path:testInfo.outputPath(`checkout-${delivery.method}-${delivery.width}.png`),fullPage:true}); await cta(page,'checkout-confirm').click(); await expect(page).toHaveURL(/checkout\/result/); await expect(page.locator('.summary-row.total')).toContainText(delivery.total); await cta(page,'order-receipt').click(); await expect(page.locator('.receipt-preview')).toContainText(delivery.total); await expect(page.locator('.receipt-preview')).toContainText('Entrega $\u00a0' + delivery.fee); await page.keyboard.press('Escape'); await cta(page,'order-list-back').click(); await expect(cta(page,'account-orders')).toHaveAttribute('aria-current','page'); await expect(cta(page,'account-orders')).toHaveClass(/current/);
 });
}

test('commercial tabs mobile cards local assets and keyboard are usable', async({page},testInfo)=>{
 await login(page,true);
 for(const width of [390,768,1440]) { await page.setViewportSize({width,height:900}); await page.goto('/demo/user/inventory'); await expect(cta(page,'inventory-adjust-DEMO-001')).toBeVisible(); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true); await page.screenshot({path:testInfo.outputPath(`inventory-cards-${width}.png`),fullPage:true}); await page.goto('/demo/user/mercadolibre'); for(const tab of ['account','listings','stock','activity','competition']) { await cta(page,`ml-tab-${tab}`).click(); await expect(page.getByRole('tabpanel')).toBeVisible(); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true); } await page.screenshot({path:testInfo.outputPath(`competition-${width}.png`),fullPage:true}); }
 await cta(page,'ml-tab-account').click(); await cta(page,'ml-tab-account').focus(); await page.keyboard.press('ArrowRight'); await expect(cta(page,'ml-tab-listings')).toBeFocused(); await expect(cta(page,'ml-tab-listings')).toHaveAttribute('aria-selected','true'); await page.keyboard.press('End'); await expect(cta(page,'ml-tab-competition')).toBeFocused();
 await page.goto('/demo/catalog/DEMO-007'); await expect(page.getByLabel('Variante',{exact:true}).locator('option')).toHaveCount(1); await expect.poll(()=>page.locator('.product-image').first().evaluate((image: HTMLImageElement)=>image.naturalWidth)).toBeGreaterThan(0); await expect(page.locator('[data-cta="related-DEMO-007"]')).toHaveCount(0); await page.screenshot({path:testInfo.outputPath('safety-product.png'),fullPage:true});
});
async function login(page: Page, admin = false) { await page.goto('/demo/login'); await page.getByLabel('Contraseña', { exact: true }).fill('demo'); await cta(page, 'login-submit').click(); await cta(page, admin ? 'login-admin' : 'login-customer').click(); }
test.beforeEach(async ({ page }) => { await page.route('**/*', route => { const url = new URL(route.request().url()); if (url.hostname !== '127.0.0.1' || url.pathname.startsWith('/api')) throw new Error(`Unexpected network request: ${url}`); return route.continue(); }); });
test('buy → stock → order → shipment, with no backend', async ({ page }) => {
 const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); await login(page);
 await page.goto('/demo/catalog/DEMO-001'); await cta(page, 'product-add-cart').click(); await expect(cta(page, 'shell-cart')).toContainText('1'); await cta(page, 'product-review-cart').click(); await expect(page.getByRole('heading', { name: 'Taladro inalámbrico 20 V' })).toBeVisible(); await cta(page, 'cart-checkout').click(); await page.getByRole('radio').check(); await cta(page, 'checkout-step-next').click(); await page.getByRole('checkbox').check(); await cta(page, 'checkout-step-next').click(); await cta(page, 'checkout-confirm').click(); await expect(page).toHaveURL(/checkout\/result\/DEMO-/); await expect(page.getByRole('heading', { name: 'Aprobado · Preparando' })).toBeVisible();
 const orderId = page.url().split('/').at(-1)!; await login(page, true); await page.goto(`/demo/user/orders/${orderId}`); await cta(page, 'order-shipment-advance').click(); await cta(page, 'operation-confirm').click(); await expect(page.getByRole('heading', { name: 'Aprobado · Enviado' })).toBeVisible(); await cta(page, 'order-shipment-advance').click(); await cta(page, 'operation-confirm').click(); await expect(page.getByRole('heading', { name: 'Aprobado · Entregado' })).toBeVisible(); await page.goto('/demo/user/inventory'); await expect(page.getByRole('row').filter({ hasText: 'DEMO-001' })).toContainText('17'); expect(errors).toEqual([]);
});
test('all 24 routes have a visible surface and inventoried interactive CTAs', async ({ page }, testInfo) => {
 await login(page); const inventory: { route: string; actions: string[] }[] = [];
 for (const screen of DemoScreen.all.filter(screen => !screen.admin)) { const path = screen.path.replace(':sku','DEMO-001').replace(':id','DEMO-100').replace(':orderId','DEMO-100'); await page.goto(`/demo/${path}`); await expect(page.locator('main h1')).toBeVisible(); inventory.push({ route: path, actions: await page.locator('[data-cta]:visible').evaluateAll(elements => elements.map(element => element.getAttribute('data-cta')!)) }); }
 await login(page,true);
 for (const screen of DemoScreen.all.filter(screen => screen.admin)) { const path = screen.path.replace(':id','DEMO-100'); await page.goto(`/demo/${path}`); await expect(page.locator('main h1')).toBeVisible(); const untracked = await page.locator('main button:visible, main a:visible').evaluateAll(elements => elements.filter(element => !element.hasAttribute('data-cta')).map(element => element.outerHTML)); expect(untracked).toEqual([]); inventory.push({ route: path, actions: await page.locator('[data-cta]:visible').evaluateAll(elements => elements.map(element => element.getAttribute('data-cta')!)) }); }
 expect(inventory).toHaveLength(24); await testInfo.attach('route-cta-inventory', { body: JSON.stringify(inventory,null,2), contentType: 'application/json' });
});
test('admin edits are reflected in storefront and ML sale is deduplicated', async ({ page }) => {
 await login(page,true); await page.goto('/demo/user/content'); await page.getByLabel('Título principal').fill('Tu próximo proyecto comienza acá'); await cta(page,'content-save').click(); await cta(page,'content-preview').click(); await expect(page.getByRole('heading',{name:'Tu próximo proyecto comienza acá'})).toBeVisible();
 await page.goto('/demo/user/mercadolibre'); await cta(page,'ml-connect').click(); await cta(page,'ml-tab-listings').click(); await cta(page,'ml-sale-DEMO-001').click(); await cta(page,'ml-sale-DEMO-001').click(); await page.goto('/demo/user/inventory'); const row=page.getByRole('row').filter({hasText:'DEMO-001'}); await expect(row).toContainText('17'); await cta(page,'inventory-adjust-DEMO-001').click(); await page.getByLabel('Unidades').fill('3'); await page.getByLabel('Motivo').fill('Ingreso demo'); await cta(page,'adjustment-save').click(); await expect(row).toContainText('20');
});
for (const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900}]) {
 test(`responsive design ${viewport.width}`,async({page},testInfo)=>{ await page.setViewportSize(viewport); await page.goto('/demo'); await expect(page.getByRole('heading',{name:'Todo para tu próximo proyecto'})).toBeVisible(); expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth+1)).toBe(true); await page.screenshot({path:testInfo.outputPath(`storefront-${viewport.width}.png`),fullPage:true}); const axe=await new AxeBuilder({page}).analyze(); expect(axe.violations).toEqual([]); await login(page,true); await page.goto('/demo/user/home'); expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth+1)).toBe(true); await page.screenshot({path:testInfo.outputPath(`dashboard-${viewport.width}.png`),fullPage:true}); });
}
test('offer changes storefront/cart, modal Escape restores focus and reset restores baseline', async ({ page }) => {
 await login(page,true); await page.goto('/demo/user/offers'); await cta(page,'campaign-edit-offer-1').click(); await expect(page.getByRole('dialog')).toBeVisible(); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).not.toBeVisible(); await expect(cta(page,'campaign-edit-offer-1')).toBeFocused();
 await cta(page,'campaign-edit-offer-1').click(); await page.getByLabel('Descuento %').fill('20'); await cta(page,'campaign-save').click(); await login(page); await page.goto('/demo/catalog/DEMO-001'); await expect(page.locator('.large-price')).toContainText('10.000'); await cta(page,'product-add-cart').click(); await cta(page,'product-review-cart').click(); await expect(page.locator('.total')).toContainText('10.000');
 await cta(page,'shell-reset-open').click(); await cta(page,'shell-reset-cancel').click(); await expect(cta(page,'shell-reset-open')).toBeFocused(); await cta(page,'shell-reset-open').click(); await cta(page,'shell-reset-confirm').click(); await expect(page).toHaveURL(/demo\/login/); await login(page); await page.goto('/demo/catalog/DEMO-001'); await expect(page.locator('.large-price')).toContainText('11.250'); await expect(cta(page,'shell-cart')).toContainText('0');
});
test('customer sees fulfillment changes and competitor history/alert has visible outcome', async ({ page }) => {
 await login(page,true); await page.goto('/demo/user/orders/DEMO-100'); await cta(page,'order-shipment-advance').click(); await cta(page,'operation-confirm').click(); await login(page); await page.goto('/demo/customer/orders/DEMO-100'); await expect(page.getByRole('heading',{name:'Aprobado · Enviado'})).toBeVisible(); await expect(page.locator('.timeline')).toContainText('Enviado');
 await login(page,true); await page.goto('/demo/user/mercadolibre'); await expect(page.locator('.demo-note')).toContainText('simulados'); await cta(page,'ml-tab-competition').click(); await cta(page,'competitor-simulate').click(); await expect(page.locator('.competitor')).toContainText('Nueva alerta'); await cta(page,'competitor-history-competitor-1').click(); await expect(page.getByRole('dialog')).toContainText('Historial simulado'); await page.keyboard.press('Escape'); await cta(page,'competitor-acknowledge').click(); await expect(page.locator('.competitor')).toContainText('Leída');
});
