import { expect, Page, test } from '@playwright/test';
import { readFileSync } from 'node:fs';

const action = (page: Page, id: string) => page.locator(`[data-cta="${id}"]`);
const path = (page: Page, route: string) => page.goto(`/demo/${route}`);
async function login(page: Page, admin = false, email = 'cliente@demo.invalid') { await path(page,'login'); await page.getByLabel('Email',{exact:true}).fill(email); await page.getByLabel('Contraseña',{exact:true}).fill('demo'); await action(page,'login-submit').click(); await action(page,admin ? 'login-admin' : 'login-customer').click(); }
async function confirm(page: Page) { await action(page,'operation-confirm').click(); }
const observed = new Set<string>();
const executed = new Set<string>();

test('commercial payment shipping channel tabs and watchlist actions', async ({page}) => {
 test.setTimeout(120000); await login(page);
 await path(page,'customer/orders'); await action(page,'return-queue-filter').selectOption('requested'); await expect(page.getByRole('region',{name:'Cola de postventa'})).toContainText('0 solicitudes'); await action(page,'return-queue-filter').selectOption('all');
 for(const id of ['account-profile','account-addresses','account-favorites','account-orders']) { await path(page,'customer/profile'); await action(page,id).click(); await expect(page.locator('main h1')).toBeVisible(); }
 await path(page,'catalog/DEMO-002'); await action(page,'related-DEMO-001').click();
 await action(page,'product-add-cart').click(); await path(page,'checkout'); await action(page,'checkout-destination').selectOption('home'); await page.getByRole('radio').check(); await action(page,'checkout-step-next').click(); await action(page,'checkout-delivery-method').selectOption('pickup'); await action(page,'checkout-step-next').click();
 for(const method of ['qr','transfer','card']) { await action(page,'checkout-payment-method').selectOption(method); await expect(page.locator('.payment-preview')).toBeVisible(); }
 await action(page,'checkout-confirm').click(); await expect(page.getByRole('status')).toContainText('Procesando'); await action(page,'checkout-payment-cancel').click(); await expect(page.getByRole('status')).toContainText('cancelado'); await expect(action(page,'shell-cart')).toContainText('1');
 await action(page,'shell-scenario').selectOption('pending'); await action(page,'checkout-confirm').click(); await expect(page).toHaveURL(/checkout\/result/); const pendingId=page.url().split('/').at(-1)!; await path(page,'customer/orders'); await action(page,`order-open-${pendingId}`).click(); await path(page,'customer/orders'); await action(page,`order-alert-payment-${pendingId}`).click(); await action(page,'order-payment-cancel').click(); await confirm(page); await expect(page.getByRole('heading',{name:'Cancelado · Preparando'})).toBeVisible(); await action(page,'order-payment-retry').click(); await expect(page).toHaveURL(/cart/);
 await action(page,'shell-scenario').selectOption('approved'); await path(page,'checkout'); await page.getByRole('radio').check(); await action(page,'checkout-step-next').click(); await page.getByRole('checkbox').check(); await action(page,'checkout-step-next').click(); await action(page,'checkout-payment-method').selectOption('qr'); await action(page,'checkout-confirm').click(); await expect(page).toHaveURL(/checkout\/result/); const approvedId=page.url().split('/').at(-1)!;
 await action(page,'order-incident-open').click(); await page.getByLabel('Detalle de incidencia').fill('Destinatario ausente'); await action(page,'incident-save').click(); await expect(page.locator('.notice.error').filter({hasText:'Destinatario ausente'})).toBeVisible(); await path(page,'customer/orders'); await action(page,`order-open-${approvedId}`).click(); await path(page,'customer/orders'); await action(page,`order-alert-incident-${approvedId}`).click();
 await action(page,'order-receipt').click(); const download=page.waitForEvent('download'); await action(page,'receipt-download').click(); expect((await download).suggestedFilename()).toContain('comprobante-demo'); await page.evaluate(()=>{window.print=()=>{document.documentElement.dataset['printed']='yes';};}); await action(page,'receipt-print').click(); await expect(page.locator('html')).toHaveAttribute('data-printed','yes'); await action(page,'dialog-close').click();
 await login(page,true); const dashboardIds=await page.locator('[data-cta^="dashboard-order-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!)); for(const id of dashboardIds) { await path(page,'user/home'); await action(page,id).click(); await expect(page.locator('main h1')).toBeVisible(); } await path(page,`user/orders/${approvedId}`); await action(page,'order-incident-resolve').click(); await expect(page.locator('.timeline')).toContainText('Incidencia resuelta');
 await path(page,'user/mercadolibre'); await action(page,'ml-connect').click(); await action(page,'ml-account-listings').click(); await action(page,'ml-process-stock').click(); await action(page,'ml-tab-stock').click(); await expect(page.getByRole('tabpanel')).toContainText('Confirmado'); await action(page,'ml-tab-activity').click(); await action(page,'ml-activity-process').click(); await expect(page.getByRole('tabpanel')).toContainText('Confirmado'); await action(page,'ml-tab-account').click(); await action(page,'ml-account-stock').click(); await action(page,'ml-tab-competition').click();
 await page.getByLabel('Comercio a observar').fill('Competidor dos'); await page.getByLabel('Umbral de alerta').fill('5'); await action(page,'competitor-watch-add').click(); await expect(page.locator('.competitor')).toContainText('Competidor dos');
 for(const id of await page.locator('[data-cta^="competitor-history-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) { await action(page,id).click(); await action(page,'information-close').click(); }
 for(const id of await page.locator('[data-cta^="competitor-change-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) await action(page,id).click();
 for(const id of await page.locator('[data-cta^="competitor-toggle-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) { await action(page,id).click(); await action(page,id).click(); }
 for(const id of await page.locator('[data-cta^="competitor-remove-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) { await action(page,id).click(); await confirm(page); }
 expect(pendingId).not.toBe(approvedId);
});
test.beforeEach(async({page})=>{
 await page.exposeFunction('recordCta',(id:string)=>executed.add(id));
 await page.exposeFunction('observeCta',(ids:string[])=>ids.forEach(id=>observed.add(id)));
 await page.addInitScript(()=>{ const reporter=window as unknown as { recordCta:(id:string)=>void; observeCta:(ids:string[])=>void }; const record=(event:Event)=>{const element=event.target instanceof Element ? event.target.closest('[data-cta]') : null; if(element) reporter.recordCta(element.getAttribute('data-cta')!);}; document.addEventListener('click',record); document.addEventListener('change',record); const collect=()=>reporter.observeCta(Array.from(document.querySelectorAll<HTMLElement>('[data-cta]')).filter(element=>(element.offsetWidth || element.offsetHeight) && !element.closest('sc-demo-fulfillment,sc-demo-inbox')).map(element=>element.getAttribute('data-cta')!)); new MutationObserver(collect).observe(document,{childList:true,subtree:true,attributes:true}); });
 await page.route('**/*',route=>{const url=new URL(route.request().url()); if(url.hostname!=='127.0.0.1'||url.pathname.startsWith('/api')) throw new Error('Forbidden demo network'); return route.continue();});
});
test.afterAll(async({browser},testInfo)=>{ expect(browser.isConnected()).toBe(true); const source=readFileSync('src/app/demo/demo-page.html','utf8')+readFileSync('src/app/demo/demo-shell.html','utf8')+readFileSync('src/app/demo/demo-product-editor.html','utf8'); const staticIds=[...source.matchAll(/data-cta="([^"]+)"/g)].map(match=>match[1]); const unexecuted=[...new Set([...observed,...staticIds])].filter(id=>!executed.has(id)).sort(); await testInfo.attach('executed-cta-matrix',{body:JSON.stringify({observed:[...observed].sort(),executed:[...executed].sort(),staticIds:[...new Set(staticIds)].sort(),unexecuted},null,2),contentType:'application/json'}); expect(unexecuted,'Every rendered CTA and every static CTA must have an executed scenario').toEqual([]); });

test('storefront controls, navigation and all product CTAs',async({page})=>{
 test.setTimeout(90000); await login(page); await path(page,'');
 for(const id of ['shell-brand','shell-catalog','shell-tools','shell-safety','shell-organization','shell-orders','shell-admin','shell-account','shell-cart','footer-contact','footer-shipping','footer-orders','home-shop','home-all-categories','home-all-products']) { await path(page,''); await action(page,id).click(); await expect(page.locator('main h1')).toBeVisible(); }
 for(const category of ['Herramientas','Seguridad','Organización']) { await path(page,''); await action(page,`home-category-${category}`).click(); await expect(page.getByLabel('Categoría',{exact:true})).toHaveValue(category); }
 await path(page,''); await page.getByLabel('Buscar productos',{exact:true}).fill('Taladro'); await action(page,'shell-search').click(); await expect(page.getByLabel('Buscar',{exact:true})).toHaveValue('Taladro');
 await path(page,'catalog'); await page.getByLabel('Buscar',{exact:true}).fill('nada'); await expect(page.getByRole('heading',{name:'No encontramos productos'})).toBeVisible(); await action(page,'empty-clear').click(); await expect(page.locator('.product-card')).toHaveCount(6);
 await page.getByLabel('Categoría',{exact:true}).selectOption('Seguridad'); await expect(page.locator('.product-card')).toHaveCount(3); await page.getByLabel('Marca',{exact:true}).selectOption('Norte'); await expect(page.locator('.product-card')).toHaveCount(1); await action(page,'catalog-filter-clear').click(); await page.getByLabel('Hasta $',{exact:true}).fill('15000'); await expect(page.locator('.product-card')).toHaveCount(1); await action(page,'catalog-filter-clear').click(); await page.getByLabel('Con stock',{exact:true}).check(); await expect(page.locator('.muted').filter({hasText:'11 productos encontrados'})).toBeVisible(); await page.getByLabel('Ordenar',{exact:true}).selectOption('price-down'); await expect(page.locator('.product-card').first()).toContainText('Cinta métrica'); await action(page,'catalog-filter-clear').click();
 await action(page,'catalog-page-next').click(); await expect(page.locator('.pagination')).toContainText('Página 2'); await action(page,'catalog-page-previous').click();
 for(const sku of ['DEMO-001','DEMO-002','DEMO-003','DEMO-004','DEMO-005','DEMO-006','DEMO-007','DEMO-008','DEMO-009','DEMO-010','DEMO-011','DEMO-012']) { await path(page,'catalog'); if(Number(sku.slice(-3))>6) await action(page,'catalog-page-next').click(); await action(page,`favorite-${sku}`).click(); await action(page,`product-open-${sku}`).click(); await expect(page.locator('main h1')).toBeVisible(); await action(page,'product-back').click(); if(Number(sku.slice(-3))>6) await action(page,'catalog-page-next').click(); await action(page,`product-name-${sku}`).click(); }
 await path(page,'catalog/DEMO-001'); await page.getByLabel('Variante',{exact:true}).selectOption('DEMO-001:standard'); await action(page,'product-favorite').click(); for(const sku of ['DEMO-002','DEMO-003','DEMO-004','DEMO-005']) { await path(page,'catalog/DEMO-001'); await action(page,`related-${sku}`).click(); await expect(page.locator('main h1')).toBeVisible(); }
 for(const sku of Array.from({length:12},(_,index)=>`DEMO-${String(index+1).padStart(3,'0')}`)) { await path(page,`catalog/${sku}`); const ids=await page.locator('[data-cta^="related-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!)); for(const id of ids) { await path(page,`catalog/${sku}`); await action(page,id).click(); await expect(page.locator('main h1')).toBeVisible(); } }
 await page.setViewportSize({width:390,height:844}); await action(page,'shell-menu').click(); await expect(page.locator('.main-nav')).toBeVisible(); await action(page,'shell-menu').click(); await expect(page.locator('.main-nav')).not.toBeVisible();
});

test('identity, profile, addresses, favorites and cart controls',async({page})=>{
 test.setTimeout(90000); await path(page,'login'); await action(page,'login-password-toggle').click(); await expect(page.getByLabel('Contraseña',{exact:true})).toHaveAttribute('type','text'); await page.getByLabel('Contraseña',{exact:true}).fill('demo'); await action(page,'login-submit').click(); await action(page,'login-context-cancel').click(); await expect(action(page,'login-customer')).not.toBeVisible(); await action(page,'login-register-link').click(); await page.getByLabel('Nombre',{exact:true}).fill('Nuevo'); await page.getByLabel('Email',{exact:true}).fill('nuevo@demo.invalid'); await page.getByLabel('Contraseña',{exact:true}).fill('demo'); await action(page,'login-submit').click(); await expect(page).toHaveURL(/customer\/profile/); await action(page,'shell-logout').click(); await login(page,false,'nuevo@demo.invalid'); await path(page,'customer/profile'); await expect(page.getByLabel('Nombre',{exact:true})).toHaveValue('Nuevo');
 await login(page); await path(page,'customer/profile'); await page.getByLabel('Nombre',{exact:true}).fill('Editado'); await action(page,'profile-cancel').click(); await expect(page.getByLabel('Nombre',{exact:true})).toHaveValue('Alex'); await page.getByLabel('Nombre',{exact:true}).fill('Alex actualizado'); await page.getByLabel('Teléfono',{exact:true}).fill('12345'); await action(page,'profile-save').click(); await page.reload(); await expect(page.getByLabel('Nombre',{exact:true})).toHaveValue('Alex actualizado');
 for(const id of ['profile-addresses','profile-favorites','profile-orders']) { await path(page,'customer/profile'); await action(page,id).click(); await expect(page.locator('main h1')).toBeVisible(); }
 await path(page,'customer/addresses'); await action(page,'address-create').click(); await action(page,'address-cancel').click(); await expect(page.getByRole('dialog')).not.toBeVisible(); await action(page,'address-create').click(); await page.getByLabel('Calle y número').fill('Calle Demo 456'); await page.getByLabel('Ciudad',{exact:true}).fill('Córdoba'); await page.getByLabel('Código postal',{exact:true}).fill('5000'); await action(page,'address-save').click(); await expect(page.locator('.address-grid')).toContainText('Calle Demo 456');
 for(const id of await page.locator('[data-cta^="address-edit-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) { await action(page,id).click(); await page.getByLabel('Nombre de la dirección').fill('Trabajo'); await action(page,'address-save').click(); }
 for(const id of await page.locator('[data-cta^="address-primary-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) await action(page,id).click();
 for(const id of await page.locator('[data-cta^="address-delete-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) { await action(page,id).click(); await action(page,'operation-cancel').click(); await action(page,id).click(); await confirm(page); }
 await path(page,'customer/favorites'); for(const sku of ['DEMO-001','DEMO-003']) { await action(page,`product-open-${sku}`).click(); await path(page,'customer/favorites'); await action(page,`product-name-${sku}`).click(); await path(page,'customer/favorites'); await action(page,`favorite-${sku}`).click(); } await action(page,'empty-catalog').click();
 await path(page,'cart'); await action(page,'cart-empty-catalog').click(); await path(page,'catalog/DEMO-001'); await action(page,'product-add-cart').click(); await action(page,'product-review-cart').click(); await page.getByLabel('Cantidad',{exact:true}).fill('2'); await expect(action(page,'shell-cart')).toContainText('2'); await action(page,'cart-remove-DEMO-001:standard').click(); await action(page,'cart-restore').click(); await expect(action(page,'shell-cart')).toContainText('2'); await action(page,'cart-continue').click(); await expect(page).toHaveURL(/catalog/);
});

test('checkout all deterministic outcomes and order actions',async({page})=>{
 test.setTimeout(90000); await login(page);
 for(const scenario of ['approved','pending','rejected','error','no-stock']) {
  await path(page,'catalog/DEMO-001'); await action(page,'product-add-cart').click(); await action(page,'product-review-cart').click(); await action(page,'cart-checkout').click(); await action(page,'checkout-address-add').click(); await action(page,'dialog-close').click(); await page.getByRole('radio').check(); await action(page,'checkout-step-next').click(); await action(page,'checkout-step-back').click(); await action(page,'checkout-step-next').click(); await page.getByRole('checkbox').check(); await action(page,'checkout-step-next').click(); await action(page,'shell-scenario').selectOption(scenario); await action(page,'checkout-confirm').click();
  if(scenario==='error'||scenario==='no-stock') { await expect(page.locator('.notice.error').first()).toBeVisible(); if(scenario==='error') { await action(page,'shell-error-reload').click(); await page.getByRole('radio').check(); await action(page,'checkout-step-next').click(); await page.getByRole('checkbox').check(); await action(page,'checkout-step-next').click(); } await action(page,'shell-scenario').selectOption('approved'); await action(page,'checkout-confirm').click(); }
  await expect(page).toHaveURL(/checkout\/result/);
  if(scenario==='pending') { await action(page,'shell-scenario').selectOption('approved'); await action(page,'order-payment-resolve').click(); await expect(page.getByRole('heading',{name:'Aprobado · Preparando'})).toBeVisible(); }
  if(scenario==='rejected') { await action(page,'order-payment-retry').click(); await expect(page).toHaveURL(/cart/); await action(page,'cart-remove-DEMO-001:standard').click(); } else { await action(page,'order-receipt').click(); await expect(page.getByRole('dialog')).toContainText('NO FISCAL'); await action(page,'dialog-close').click(); await action(page,'order-list-back').click(); }
 }
 await path(page,'customer/orders'); await page.getByLabel('Estado de pago',{exact:true}).selectOption('APPROVED'); await page.getByLabel('Buscar pedido',{exact:true}).fill('DEMO-100'); await action(page,'order-open-DEMO-100').click(); await action(page,'order-continue-shop').click(); await path(page,'customer/orders/DEMO-101'); await action(page,'order-tracking').click(); await action(page,'dialog-close').click();
 await path(page,'checkout'); await action(page,'checkout-edit-cart').click(); await path(page,'customer/orders'); for(const id of await page.locator('[data-cta^="order-open-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) { await action(page,id).click(); await expect(page.locator('main h1')).toBeVisible(); await action(page,'order-list-back').click(); }
});

test('admin editors, inventory, offers, fulfillment, ML and configuration CTAs',async({page})=>{
 test.setTimeout(120000); await login(page,true);
 for(const id of await page.locator('[data-cta^="admin-nav-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!))) { await action(page,id).click(); await expect(page.locator('main h1')).toBeVisible(); }
 for(const id of ['dashboard-alert-payments','dashboard-alert-stock','dashboard-alert-channel','dashboard-revenue','dashboard-orders','dashboard-low-stock','dashboard-products','dashboard-inventory','dashboard-content','dashboard-offers','dashboard-order-DEMO-100','dashboard-order-DEMO-101','dashboard-order-DEMO-102']) { await path(page,'user/home'); await action(page,id).click(); await expect(page.locator('main h1')).toBeVisible(); }
 await path(page,'user/home'); await action(page,'admin-store-preview').click(); await expect(page.getByRole('heading',{name:'Todo para tu próximo proyecto'})).toBeVisible();
 await path(page,'user/content'); await page.getByLabel('Título principal').fill('Borrador'); await action(page,'content-cancel').click(); await expect(page.getByLabel('Título principal')).toHaveValue('Todo para tu próximo proyecto'); await page.getByLabel('Título principal').fill('Nuevo contenido'); await action(page,'content-save').click(); await action(page,'content-preview').click(); await expect(page.getByRole('heading',{name:'Nuevo contenido'})).toBeVisible();
 await path(page,'user/catalog'); await action(page,'admin-product-create').click(); await action(page,'product-cancel').click(); await action(page,'admin-product-create').click(); await page.getByLabel('Nombre',{exact:true}).fill('Producto creado'); await page.getByLabel('Marca',{exact:true}).fill('Marca de muestra'); await page.getByLabel('Descripción',{exact:true}).fill('Descripción de producto creado'); await page.getByLabel('Precio ($)',{exact:true}).fill('25000'); await action(page,'product-save').click(); await expect(page.locator('table')).toContainText('Producto creado');
 for(const sku of await page.locator('[data-cta^="admin-product-edit-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!.replace('admin-product-edit-','')))) { await action(page,`admin-product-edit-${sku}`).click(); const removals=await page.locator('[data-cta^="product-image-remove-"],[data-cta^="variant-image-remove-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!)); for(const id of removals) await action(page,id).click(); await action(page,'product-cancel').click(); await action(page,`admin-product-edit-${sku}`).click(); await action(page,'product-save').click(); await action(page,`admin-product-archive-${sku}`).click(); await action(page,'operation-cancel').click(); await action(page,`admin-product-archive-${sku}`).click(); await confirm(page); await action(page,`admin-product-archive-${sku}`).click(); await confirm(page); await action(page,`admin-product-preview-${sku}`).click(); await path(page,'user/catalog'); }
 await page.getByLabel('Buscar',{exact:true}).fill('Producto creado'); await expect(page.locator('tbody tr')).toHaveCount(1);
 await path(page,'user/offers'); await action(page,'campaign-create').click(); await action(page,'campaign-cancel').click(); await action(page,'campaign-edit-offer-1').click(); await page.getByLabel('Descuento %').fill('15'); await action(page,'campaign-save').click(); await action(page,'campaign-toggle-offer-1').click(); await expect(page.locator('.address-grid')).toContainText('Pausada'); await action(page,'campaign-toggle-offer-1').click(); await action(page,'campaign-preview-offer-1').click(); await path(page,'user/promos'); await action(page,'campaign-create').click(); await page.getByLabel('Título',{exact:true}).fill('Campaña nueva'); await action(page,'campaign-save').click(); await expect(page.locator('.address-grid')).toContainText('Campaña nueva'); const newCampaignEdit=await page.locator('[data-cta^="campaign-edit-"]').last().getAttribute('data-cta'); const newCampaignId=newCampaignEdit!.replace('campaign-edit-',''); await action(page,newCampaignEdit!).click(); await action(page,'campaign-save').click(); await action(page,`campaign-toggle-${newCampaignId}`).click(); await action(page,`campaign-preview-${newCampaignId}`).click();
 await path(page,'user/inventory'); for(const sku of await page.locator('[data-cta^="inventory-adjust-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!.replace('inventory-adjust-','')))) { await action(page,`inventory-adjust-${sku}`).click(); await action(page,'adjustment-cancel').click(); await action(page,`inventory-adjust-${sku}`).click(); await page.getByLabel('Unidades').fill('1'); await page.getByLabel('Motivo').fill('Reposición de muestra'); await action(page,'adjustment-save').click(); await action(page,`inventory-movements-${sku}`).click(); await expect(page.getByRole('dialog')).toContainText('Reposición de muestra'); await action(page,'information-close').click(); }
 await path(page,'user/orders'); for(const id of ['DEMO-100','DEMO-101','DEMO-102']) { await action(page,`order-open-${id}`).click(); if(id!=='DEMO-102') { await action(page,'order-shipment-advance').click(); await action(page,'operation-cancel').click(); await action(page,'order-shipment-advance').click(); await confirm(page); } else { await expect(page.getByRole('region',{name:'Postventa del pedido'})).toBeVisible(); await expect(action(page,'order-return-receive')).toHaveCount(0); } await action(page,'order-list-back').click(); }
 await path(page,'user/mercadolibre'); await action(page,'ml-connect').click(); await action(page,'ml-tab-listings').click(); for(const sku of ['DEMO-001','DEMO-002','DEMO-003','DEMO-004','DEMO-005','DEMO-006']) { await action(page,`ml-link-${sku}`).click(); if(Number(sku.slice(-3))<=4) await action(page,`ml-link-${sku}`).click(); await action(page,`ml-sync-${sku}`).click(); await action(page,`ml-sale-${sku}`).click(); await action(page,`ml-inspect-${sku}`).click(); await action(page,'information-close').click(); } await action(page,'shell-scenario').selectOption('error'); await action(page,'ml-link-DEMO-001').click(); await action(page,'ml-link-DEMO-001').click(); await action(page,'ml-sync-DEMO-001').click(); await expect(page.getByRole('row').filter({hasText:'Taladro'})).toContainText('Error'); await action(page,'shell-scenario').selectOption('approved'); await action(page,'ml-sync-DEMO-001').click(); await action(page,'ml-tab-competition').click(); await action(page,'competitor-simulate').click(); await action(page,'competitor-history-competitor-1').click(); await action(page,'information-close').click(); await action(page,'competitor-acknowledge').click(); await action(page,'ml-tab-account').click(); await action(page,'ml-connect').click();
 await path(page,'user/capabilities'); for(const id of ['Catálogo','Checkout','Envíos','Mercado Libre']) { await action(page,`module-toggle-${id}`).click(); await confirm(page); await action(page,`module-inspect-${id}`).click(); await action(page,'information-close').click(); }
 await path(page,'user/profile-import'); await action(page,'configuration-sample').click(); await action(page,'configuration-validate').click(); await expect(page.getByRole('dialog')).toContainText('Perfil válido'); await action(page,'information-close').click(); await action(page,'configuration-import').click(); await action(page,'operation-cancel').click(); await action(page,'configuration-import').click(); await confirm(page); await expect(page.locator('.commerce-layout')).toContainText('Tu taller, mejor equipado'); const download=page.waitForEvent('download'); await action(page,'configuration-export').click(); expect((await download).suggestedFilename()).toBe('comercio-demo.json'); await action(page,'configuration-cancel').click(); await expect(page.getByLabel('Perfil',{exact:true})).toHaveValue('');
 await action(page,'shell-reset-open').click(); await action(page,'shell-reset-cancel').click(); await action(page,'shell-reset-open').click(); await action(page,'shell-reset-confirm').click(); await expect(page).toHaveURL(/login/); await path(page,'user/home'); await action(page,'access-login').click(); await expect(page).toHaveURL(/login/);
});
test('missing entity recovery, forbidden context and actor isolation',async({page})=>{
 await login(page); await path(page,'catalog/unknown-product'); await action(page,'missing-product-catalog').click(); await expect(page).toHaveURL(/catalog/); await path(page,'customer/orders/unknown-order'); await action(page,'missing-order-list').click(); await expect(page).toHaveURL(/customer\/orders/); await path(page,'user/home'); await action(page,'access-login').click(); await expect(page).toHaveURL(/login/);
 await login(page,false,'cliente2@demo.invalid'); await path(page,'customer/orders'); await expect(page.locator('table')).toContainText('DEMO-102'); await expect(page.locator('table')).not.toContainText('DEMO-100'); await path(page,'customer/orders/DEMO-100'); await expect(page.getByRole('heading',{name:'Pedido no disponible'})).toBeVisible(); await action(page,'missing-order-list').click(); await expect(page.locator('table')).not.toContainText('DEMO-100');
});
test('gallery, priced variants, ordered content and module settings are stateful',async({page})=>{
 await login(page); await path(page,'catalog/DEMO-001'); const firstImage=await page.locator('.product-art.large img').getAttribute('src'); await action(page,'gallery-1').click(); await expect(page.locator('.product-art.large img')).not.toHaveAttribute('src',firstImage!); await action(page,'gallery-0').click(); await expect(page.locator('.product-art.large img')).toHaveAttribute('src',firstImage!); await action(page,'product-variant').selectOption('DEMO-001:with-case'); await expect(page.locator('.large-price')).toContainText('13.500'); await action(page,'product-add-cart').click(); await action(page,'product-review-cart').click(); await expect(page.locator('.cart-line')).toContainText('Con estuche de transporte'); await expect(page.locator('.total')).toContainText('13.500'); await page.reload(); await expect(page.locator('.cart-line')).toContainText('Con estuche de transporte'); await action(page,'cart-remove-DEMO-001:with-case').click(); await expect(page.locator('.cart-line')).toHaveCount(0); await action(page,'cart-restore').click(); await expect(page.locator('.cart-line')).toContainText('Con estuche de transporte');
 await login(page,true); await path(page,'user/content'); await action(page,'content-down-service').click(); await expect(page.locator('.content-block-editor').first().getByLabel('Título del bloque',{exact:true})).toHaveValue('Calidad que te acompaña'); await action(page,'content-up-service').click(); await action(page,'content-up-quality').click(); await action(page,'content-down-quality').click(); await action(page,'content-down-service').click(); await action(page,'content-save').click(); await action(page,'content-preview').click(); await expect(page.locator('[data-block]').first()).toHaveAttribute('data-block','quality');
 await path(page,'user/capabilities');
 for(const id of ['Catálogo','Checkout','Envíos','Mercado Libre']) { await action(page,`module-configure-${id}`).click(); await action(page,'module-cancel').click(); await action(page,`module-configure-${id}`).click(); if(id==='Catálogo'){ await page.getByLabel('Productos destacados en portada').fill('6'); await page.getByLabel('Umbral de stock bajo').fill('8'); } if(id==='Checkout') await page.getByLabel('Días estimados de entrega').fill('3'); if(id==='Envíos') await page.getByLabel('Prefijo de seguimiento simulado').fill('DEMOEXP'); if(id==='Mercado Libre') await page.getByLabel('Productos por vista de sincronización').fill('4'); await action(page,'module-save').click(); await action(page,`module-configure-${id}`).click(); if(id==='Checkout') await expect(page.getByLabel('Días estimados de entrega')).toHaveValue('3'); await action(page,'module-cancel').click(); }
 await path(page,''); await expect(page.locator('.product-card')).toHaveCount(6); await path(page,'user/mercadolibre'); await action(page,'ml-tab-listings').click(); await expect(page.locator('tbody tr')).toHaveCount(4);
});


test('variant editor controls and explicit price refresh have state effects',async({page})=>{
 test.setTimeout(90000); await login(page,true); const lowIds=await page.locator('[data-cta^="dashboard-variant-stock-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!)); for(const id of lowIds) { await path(page,'user/home'); await action(page,id).click(); await expect(page).toHaveURL(/inventory\?q=/); }
 await path(page,'user/inventory'); await action(page,'inventory-adjust-DEMO-001').click(); await action(page,'inventory-variant').selectOption('DEMO-001:with-case'); await page.getByLabel('Motivo',{exact:true}).fill('Ingreso de variante'); await action(page,'adjustment-save').click(); await path(page,'user/catalog'); await action(page,'admin-product-edit-DEMO-001').click();
 const productRemovals=await page.locator('[data-cta^="product-image-remove-"]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!)); for(const id of productRemovals) await action(page,id).click();
 await action(page,'product-image-add').click(); const imageRemoval=await page.locator('[data-cta^="product-image-remove-"]').getAttribute('data-cta'); await action(page,imageRemoval!).click();
 for(const index of [0,1]) { const imageIds=await page.locator(`[data-cta^="variant-image-remove-${index}-"]`).evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!)); for(const id of imageIds) await action(page,id).click(); await action(page,`variant-image-add-${index}`).click(); const newId=await page.locator(`[data-cta^="variant-image-remove-${index}-"]`).getAttribute('data-cta'); await action(page,newId!).click(); await action(page,`variant-attribute-remove-${index}-0`).click(); await action(page,`variant-attribute-add-${index}`).click(); await action(page,`variant-attribute-remove-${index}-0`).click(); await action(page,`variant-remove-${index}`).click(); await page.locator(`[name="variant-active-${index}"]`).check(); }
 await action(page,'product-variant-add').click(); await page.locator('[name="variant-name-2"]').fill('Variante archivada'); await action(page,'variant-attribute-add-2').click(); await action(page,'variant-attribute-remove-2-0').click(); await action(page,'variant-image-add-2').click(); const newImage=await page.locator('[data-cta^="variant-image-remove-2-"]').getAttribute('data-cta'); await action(page,newImage!).click(); await action(page,'variant-remove-2').click();
 await expect(page.locator('fieldset')).toHaveCount(2); await action(page,'product-cancel').click(); await action(page,'admin-product-edit-DEMO-001').click(); await expect(page.locator('fieldset')).toHaveCount(2); await action(page,'product-cancel').click();
 await action(page,'admin-product-edit-DEMO-002').click();
 for (const prefix of ['product-image-remove-','variant-image-remove-']) { const ids=await page.locator(`[data-cta^="${prefix}"]`).evaluateAll(elements=>elements.map(element=>element.getAttribute('data-cta')!)); for(const id of ids) await action(page,id).click(); }
 await action(page,'product-cancel').click();
 await login(page); await path(page,'catalog/DEMO-001'); await action(page,'gallery-zoom').click(); await expect(page.locator('.zoom-image')).toBeVisible(); await action(page,'dialog-close').click(); await action(page,'product-add-cart').click();
 await login(page,true); await path(page,'user/catalog'); await action(page,'admin-product-edit-DEMO-001').click(); await page.locator('[name="variant-price-0"]').fill('13000'); await action(page,'product-save').click(); await login(page); await path(page,'cart'); await expect(action(page,'cart-refresh')).toBeVisible(); await action(page,'cart-refresh').click(); await expect(action(page,'cart-refresh')).toHaveCount(0); await expect(page.locator('.total')).toContainText('11.700');
});
