import { test, expect, Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const cta = (page: Page, id: string) => page.locator(`[data-cta="${id}"]`);
async function login(page: Page, admin = false, email = 'cliente@demo.invalid') { await page.goto('/demo/login'); await page.getByLabel('Perfil comprador de muestra').selectOption(email); await page.getByLabel('Contraseña', { exact: true }).fill('demo'); await cta(page, 'login-submit').click(); await cta(page, admin ? 'login-admin' : 'login-customer').click(); }
async function audit(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]); }
const families = ['fulfillment-details', 'fulfillment-save', 'fulfillment-note', 'fulfillment-dispatch', 'fulfillment-failed-attempt', 'fulfillment-retry', 'fulfillment-deliver', 'fulfillment-ready', 'fulfillment-no-show', 'fulfillment-extend', 'fulfillment-new-deadline', 'fulfillment-collect', 'fulfillment-resolution', 'fulfillment-resolve', 'inbox-filter', 'inbox-read-all', 'inbox-preferences', 'inbox-preference-orders', 'inbox-preference-post-sale', 'inbox-preference-stock', 'inbox-preference-marketplace', 'inbox-read', 'inbox-open'];
const executed = new Set<string>();
test.beforeEach(async ({ page }) => {
 await page.exposeFunction('recordFulfillment', (id: string) => { const family = families.find(value => id === value || id.startsWith(value + '-')); if (family) executed.add(family); });
 await page.addInitScript(() => { const targetWindow = window as unknown as {recordFulfillment:(id:string)=>void}; const record = (event: Event) => { const target = event.target instanceof Element ? event.target.closest('[data-cta]') : null; if (target) targetWindow.recordFulfillment(target.getAttribute('data-cta')!); }; for (const type of ['click','input','change']) document.addEventListener(type,record); });
 await page.route('**/*', route => { const url = new URL(route.request().url()); expect(url.hostname).toBe('127.0.0.1'); expect(url.pathname.startsWith('/api')).toBe(false); return route.continue(); });
});
test.afterAll(async ({browser}, info) => { expect(browser.isConnected()).toBe(true); const missing = families.filter(value => !executed.has(value)); await info.attach('fulfillment-inbox-cta-trace', {body:JSON.stringify({expected:families,executed:[...executed],missing},null,2),contentType:'application/json'}); expect(missing).toEqual([]); });
for (const width of [390,768,1440]) {
 test(`home delivery recipient → dispatch → failed attempt → retry → delivery at ${width}`, async ({page},info) => {
  test.setTimeout(90000); await page.setViewportSize({width,height:900}); await login(page,true); await page.goto('/demo/user/orders/DEMO-100');
  await cta(page,'fulfillment-details').click(); await page.getByLabel('Nombre del destinatario').fill('Alex Comprador'); await page.getByLabel('Teléfono de contacto').fill('011 5555 1234'); await page.getByLabel('Transportista simulado').fill('Correo Demo'); await page.getByLabel('Servicio de envío').fill('Entrega prioritaria'); await cta(page,'fulfillment-save').click();
  await cta(page,'fulfillment-dispatch').click(); await expect(page.getByRole('region',{name:'Gestión de entrega'})).toContainText('Enviado');
  await cta(page,'fulfillment-note').fill('Domicilio sin receptor'); await cta(page,'fulfillment-failed-attempt').click(); await expect(cta(page,'fulfillment-deliver')).toHaveCount(0); await expect(page.getByRole('region',{name:'Gestión de entrega'})).toContainText('Domicilio sin receptor'); await page.reload();
  await cta(page,'fulfillment-note').fill('Nueva visita mañana de 9 a 12'); await cta(page,'fulfillment-retry').click(); await cta(page,'fulfillment-deliver').click(); await expect(page.getByRole('region',{name:'Gestión de entrega'})).toContainText('Entregado'); await audit(page); await page.screenshot({path:info.outputPath('home-delivery.png'),fullPage:true});
  await login(page); await page.goto('/demo/customer/orders/DEMO-100'); await expect(page.getByRole('region',{name:'Gestión de entrega'})).toContainText('Alex Comprador'); await expect(page.getByRole('region',{name:'Gestión de entrega'})).toContainText('Nueva visita mañana de 9 a 12'); await expect(cta(page,'fulfillment-dispatch')).toHaveCount(0); await audit(page);
  await cta(page,'order-incident-open').click(); await page.getByLabel('Detalle de incidencia').fill('Consulta del comprador sobre comprobante'); await cta(page,'incident-save').click(); await login(page,true); await page.goto('/demo/user/orders/DEMO-100'); await cta(page,'fulfillment-resolution').fill('Comprobante disponible en tu pedido'); await cta(page,'fulfillment-resolve').click(); await expect(page.getByRole('region',{name:'Gestión de entrega'})).toContainText('Comprobante disponible');
 });
 test(`pickup store → ready → no-show → extension → collection at ${width}`, async ({page},info) => {
  test.setTimeout(90000); await page.setViewportSize({width,height:900}); await login(page); await page.goto('/demo/catalog/DEMO-001'); await cta(page,'product-add-cart').click(); await page.goto('/demo/cart'); await cta(page,'cart-checkout').click(); await page.getByRole('radio').check(); await cta(page,'checkout-step-next').click(); await cta(page,'checkout-delivery-method').selectOption('pickup'); await cta(page,'checkout-step-next').click(); await cta(page,'checkout-confirm').click(); await expect(page).toHaveURL(/checkout\/result/); const id = page.url().split('/').at(-1)!;
  await login(page,true); await page.goto(`/demo/user/orders/${id}`); await cta(page,'fulfillment-details').click(); await page.getByLabel('Sucursal',{exact:true}).fill('Sucursal Norte'); await page.getByLabel('Dirección de retiro',{exact:true}).fill('Calle Norte 123'); await page.getByLabel('Horarios de retiro').fill('Lunes a viernes de 9 a 17'); await page.getByLabel('Último día para retirar').fill('2026-12-31'); await cta(page,'fulfillment-save').click(); await cta(page,'fulfillment-ready').click(); await expect(cta(page,'fulfillment-dispatch')).toHaveCount(0);
  await cta(page,'fulfillment-note').fill('No se presentó al retirar'); await cta(page,'fulfillment-no-show').click(); await expect(cta(page,'fulfillment-collect')).toHaveCount(0); await page.reload(); await cta(page,'fulfillment-note').fill('Retiro coordinado el próximo viernes'); await cta(page,'fulfillment-new-deadline').fill('2027-01-07'); await cta(page,'fulfillment-extend').click(); await cta(page,'fulfillment-collect').click(); await expect(page.getByRole('region',{name:'Gestión de entrega'})).toContainText('Retirado por el comprador'); await audit(page); await page.screenshot({path:info.outputPath('pickup.png'),fullPage:true});
  await login(page); await page.goto(`/demo/customer/orders/${id}`); await expect(page.getByRole('region',{name:'Gestión de entrega'})).toContainText('Sucursal Norte'); await expect(page.getByRole('heading',{name:'Solicitar una devolución'})).toBeVisible(); await audit(page);
 });
}
test('notification history, read/unread, preferences, routes and actor isolation survive reload', async ({page},info) => {
 test.setTimeout(90000); await login(page); await page.goto('/demo/customer/orders'); const inbox = page.getByRole('region',{name:'Centro de notificaciones'}); await expect(inbox).toContainText('DEMO-100'); await expect(inbox).not.toContainText('DEMO-102'); const readButton = page.locator('sc-demo-inbox article [data-cta^="inbox-read-"]').first(); const readId = (await readButton.getAttribute('data-cta'))!; await readButton.click(); await cta(page,'inbox-filter').selectOption('read'); await expect(cta(page,readId)).toBeVisible(); await page.reload(); await cta(page,'inbox-filter').selectOption('read'); await expect(cta(page,readId)).toBeVisible(); await cta(page,readId).click(); await cta(page,'inbox-filter').selectOption('unread'); await expect(cta(page,readId)).toBeVisible();
 await cta(page,'inbox-preferences').click(); await cta(page,'inbox-preference-orders').uncheck(); await cta(page,'inbox-preference-post-sale').uncheck(); await page.reload(); await cta(page,'inbox-preferences').click(); await expect(cta(page,'inbox-preference-orders')).not.toBeChecked(); await cta(page,'inbox-preference-orders').check(); await cta(page,'inbox-preference-post-sale').check(); await cta(page,'inbox-read-all').click(); await cta(page,'inbox-filter').selectOption('all'); await page.locator('[data-cta^="inbox-open-"]').first().click(); await expect(page).toHaveURL(/customer\/orders\/DEMO/);
 await login(page,false,'cliente2@demo.invalid'); await page.goto('/demo/customer/orders'); await expect(inbox).not.toContainText('DEMO-100'); await expect(inbox).toContainText('DEMO-102'); await cta(page,'inbox-preferences').click(); await expect(cta(page,'inbox-preference-orders')).toBeChecked(); await audit(page);
 await login(page,true); await page.goto('/demo/user/home'); await cta(page,'inbox-preferences').click(); await cta(page,'inbox-preference-stock').uncheck(); await cta(page,'inbox-preference-stock').check(); await cta(page,'inbox-preference-marketplace').uncheck(); await cta(page,'inbox-preference-marketplace').check(); await audit(page); await page.screenshot({path:info.outputPath('admin-notifications.png'),fullPage:true});
 await info.attach('notification-state', {body:await page.evaluate(()=>localStorage.getItem('storecore.commercial-demo.v1') ?? ''),contentType:'application/json'});
});
