import { expect, test, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const cta = (page: Page, id: string) => page.locator(`[data-cta="${id}"]`);
const families = ['marketplace-authorize','marketplace-pause','marketplace-expire','marketplace-account-error','marketplace-mapping-save','marketplace-mapping-edit','marketplace-mapping-unlink','marketplace-stock-process','marketplace-stock-fail','marketplace-variant-new-sale','marketplace-variant-sale','marketplace-queue-retry','marketplace-observation-refresh','marketplace-observation-stale','marketplace-observation-unavailable','marketplace-observation-replay','marketplace-observation-history'];
const executed = new Set<string>();
test.beforeEach(async ({ page }) => { await page.exposeFunction('recordMarketplace', (id: string) => { const family = families.find(value => id === value || id.startsWith(value + '-')); if (family) executed.add(family); }); await page.addInitScript(() => { const reporter = window as unknown as {recordMarketplace:(id:string)=>void}; document.addEventListener('click', event => { const target = event.target instanceof Element ? event.target.closest('[data-cta]') : null; if (target) reporter.recordMarketplace(target.getAttribute('data-cta')!); }); }); await page.route('**/*', route => { const url = new URL(route.request().url()); expect(url.hostname).toBe('127.0.0.1'); expect(url.pathname.startsWith('/api')).toBe(false); return route.continue(); }); });
test.afterAll(async ({ browser }, info) => { expect(browser.isConnected()).toBe(true); const missing = families.filter(value => !executed.has(value)); await info.attach('marketplace-cta-trace', { body:JSON.stringify({expected:families,executed:[...executed],missing},null,2),contentType:'application/json' }); expect(missing).toEqual([]); });
async function admin(page: Page) { await page.goto('/demo/login'); await page.getByLabel('Contraseña', { exact: true }).fill('demo'); await cta(page, 'login-submit').click(); await cta(page, 'login-admin').click(); await page.goto('/demo/user/mercadolibre'); }
test('marketplace account pause expiry recovery and queue survive reload', async ({ page }) => {
  await admin(page); await cta(page,'marketplace-authorize').click(); await expect(page.locator('.marketplace-detail')).toContainText('Autorizada (simulada)'); await cta(page,'marketplace-pause').click(); await cta(page,'ml-tab-stock').click(); await expect(cta(page,'marketplace-stock-process')).toBeDisabled(); await page.reload(); await expect(page.locator('.marketplace-detail')).toContainText('Canal pausado'); await cta(page,'marketplace-expire').click(); await expect(page.locator('.marketplace-detail')).toContainText('vencida'); await cta(page,'marketplace-account-error').click(); await expect(page.locator('.marketplace-detail')).toContainText('Error de cuenta'); await cta(page,'marketplace-authorize').click(); await cta(page,'ml-tab-stock').click(); await cta(page,'marketplace-stock-fail').click(); await cta(page,'ml-tab-activity').click(); await expect(page.locator('.marketplace-detail')).toContainText('Error recuperable'); await cta(page,'marketplace-queue-retry').click(); await expect(page.locator('.marketplace-detail')).toContainText('Confirmado (simulado)'); await expect(page.locator('.marketplace-detail')).toContainText('Intentos 2'); await cta(page,'ml-tab-stock').click(); await cta(page,'marketplace-stock-process').click();
});
test('explicit mapping blocks duplicate targets and variant sale is exactly once', async ({ page }) => {
  await admin(page); await cta(page,'marketplace-authorize').click(); await cta(page,'ml-tab-listings').click(); await page.getByLabel('Variante local', {exact:true}).selectOption('DEMO-001:with-case'); await cta(page,'marketplace-mapping-save').click(); await expect(page.getByRole('alert')).toContainText('Conflicto'); await page.getByLabel('Variación de muestra',{exact:true}).fill('SIM-case'); await cta(page,'marketplace-mapping-save').click(); await expect(page.locator('.marketplace-detail')).toContainText('SIM-case'); await cta(page,'ml-tab-stock').click(); const before = await page.evaluate(() => JSON.parse(localStorage.getItem('storecore.commercial-demo.v1')!).products[0].variants[1].onHand); await cta(page,'marketplace-variant-new-sale-mapping-DEMO-001:with-case').click(); await cta(page,'marketplace-variant-sale-mapping-DEMO-001:with-case').click(); const after = await page.evaluate(() => JSON.parse(localStorage.getItem('storecore.commercial-demo.v1')!).products[0].variants[1].onHand); expect(after).toBe(before - 1); await cta(page,'ml-tab-listings').click(); await cta(page,'marketplace-mapping-unlink-mapping-DEMO-001:with-case').click(); await expect(page.locator('.marketplace-detail')).toContainText('Sin vincular'); await cta(page,'marketplace-mapping-edit-mapping-DEMO-001:with-case').click(); await expect(page.getByLabel('Publicación de muestra',{exact:true})).toBeFocused();
});
test('competitor freshness history replay and comparison preserve merchant price', async ({ page }) => {
  await admin(page); await cta(page,'ml-tab-competition').click(); await cta(page,'competitor-simulate').click(); const own = await page.evaluate(() => JSON.parse(localStorage.getItem('storecore.commercial-demo.v1')!).products[0].price); await cta(page,'marketplace-observation-history-competitor-1').click(); await expect(page.locator('.marketplace-detail')).toContainText('2026-10-09'); await expect(page.locator('.marketplace-detail .timeline')).toBeVisible(); const count = await page.locator('.marketplace-detail .timeline li').count(); await cta(page,'marketplace-observation-replay-competitor-1').click(); await expect(page.locator('.marketplace-detail .timeline li')).toHaveCount(count); await cta(page,'marketplace-observation-stale-competitor-1').click(); await expect(page.locator('.marketplace-detail')).toContainText('Datos desactualizados'); await cta(page,'marketplace-observation-unavailable-competitor-1').click(); await expect(page.locator('.marketplace-detail')).toContainText('no disponible'); await cta(page,'marketplace-observation-refresh-competitor-1').click(); await expect(page.locator('.marketplace-detail')).toContainText('Observación reciente'); await cta(page,'competitor-acknowledge').click(); await expect(page.locator('.competitor')).toContainText('Leída'); expect(await page.evaluate(() => JSON.parse(localStorage.getItem('storecore.commercial-demo.v1')!).products[0].price)).toBe(own); await cta(page,'marketplace-observation-history-competitor-1').click(); await expect(page.locator('.marketplace-detail .timeline')).toHaveCount(0);
});
test('completed marketplace tabs responsive and accessible', async ({ page }, info) => {
  await admin(page);
  for (const width of [390,768,1440]) { await page.setViewportSize({width,height:900}); for (const tab of ['account','listings','stock','activity','competition']) { await cta(page,`ml-tab-${tab}`).click(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); const result = await new AxeBuilder({page}).analyze(); expect(result.violations).toEqual([]); await page.screenshot({path:info.outputPath(`marketplace-${tab}-${width}.png`),fullPage:true}); } }
});
