import { test, expect, Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const cta = (page: Page, id: string) => page.locator(`[data-cta="${id}"]`);
const actionFamilies = ['return-quantity', 'return-reason', 'return-request', 'return-note', 'return-approve', 'return-reject', 'return-outcome', 'return-inspect', 'return-refund', 'return-alert', 'return-queue-filter', 'return-queue', 'return-cancel'];
const executedFamilies = new Set<string>();
async function login(page: Page, admin = false, email = 'cliente@demo.invalid') { await page.goto('/demo/login'); await page.getByLabel('Email', { exact: true }).fill(email); await page.getByLabel('Contraseña', { exact: true }).fill('demo'); await cta(page, 'login-submit').click(); await cta(page, admin ? 'login-admin' : 'login-customer').click(); }
test.beforeEach(async ({ page }) => {
 await page.exposeFunction('recordPostSaleCta', (id: string) => { const family = actionFamilies.find(value => id === value || id.startsWith(value + '-')); if (family) executedFamilies.add(family); });
 await page.addInitScript(() => { const report = window as unknown as { recordPostSaleCta: (id: string) => void }; const record = (event: Event) => { const target = event.target instanceof Element ? event.target.closest('[data-cta]') : null; if (target) report.recordPostSaleCta(target.getAttribute('data-cta')!); }; for (const type of ['click', 'input', 'change']) document.addEventListener(type, record); });
 await page.route('**/*', route => { const url = new URL(route.request().url()); expect(url.hostname).toBe('127.0.0.1'); expect(url.pathname.startsWith('/api')).toBe(false); return route.continue(); });
});
test.afterAll(async ({ browser }, info) => { expect(browser.isConnected()).toBe(true); const missing = actionFamilies.filter(value => !executedFamilies.has(value)); await info.attach('post-sale-cta-coverage', { body: JSON.stringify({ expected: actionFamilies, executed: [...executedFamilies], missing }, null, 2), contentType: 'application/json' }); expect(missing).toEqual([]); });

for (const width of [390, 768, 1440]) test(`partial return buyer → admin inspection → refund at ${width}`, async ({ page }, info) => {
 test.setTimeout(90000); await page.setViewportSize({ width, height: 900 }); await login(page);
 await page.goto('/demo/catalog/DEMO-001'); await page.getByLabel('Cantidad', { exact: true }).fill('3'); await cta(page, 'product-add-cart').click();
 await page.goto('/demo/catalog/DEMO-002'); await cta(page, 'product-add-cart').click(); await page.goto('/demo/cart'); await cta(page, 'cart-checkout').click(); await page.getByRole('radio').check(); await cta(page, 'checkout-step-next').click(); await cta(page, 'checkout-delivery-method').selectOption('pickup'); await cta(page, 'checkout-step-next').click(); await cta(page, 'checkout-confirm').click(); await expect(page).toHaveURL(/checkout\/result/); const id = page.url().split('/').at(-1)!;
 await login(page, true); await page.goto(`/demo/user/orders/${id}`); for (let step = 0; step < 2; step++) { await cta(page, 'order-shipment-advance').click(); await cta(page, 'operation-confirm').click(); }
 await login(page); await page.goto(`/demo/customer/orders/${id}`); await expect(page.getByRole('heading', { name: 'Solicitar una devolución' })).toBeVisible();
 await cta(page, 'return-quantity-DEMO-001:standard').fill('2'); await cta(page, 'return-reason-DEMO-001:standard').selectOption('damaged'); await cta(page, 'return-quantity-DEMO-002:standard').fill('1'); await cta(page, 'return-reason-DEMO-002:standard').selectOption('wrong'); await cta(page, 'return-request').click(); await expect(page.getByRole('heading', { name: 'Solicitud enviada' })).toBeVisible();
 await page.reload(); await expect(page.getByRole('heading', { name: 'Solicitud enviada' })).toBeVisible(); await expect(page.locator('[data-cta^="return-approve-"]')).toHaveCount(0);
 await page.screenshot({ path: info.outputPath('buyer-return.png'), fullPage: true }); expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
 await login(page, true); await page.goto('/demo/user/orders'); await cta(page,'return-queue-filter').selectOption('inspected'); await expect(page.getByRole('region',{name:'Cola de postventa'})).toContainText('0 solicitudes'); await cta(page,'return-queue-filter').selectOption('requested'); await expect(page.getByRole('region',{name:'Cola de postventa'})).toContainText('1 solicitudes'); await page.getByRole('link',{name:'Revisar devolución'}).click();
 const request = await page.locator('[data-cta^="return-approve-"]').getAttribute('data-cta'); const returnId = request!.slice('return-approve-'.length);
 await page.locator('[data-cta^="return-note-"]').fill('Devolución parcial aprobada para inspección'); await cta(page, `return-approve-${returnId}`).click(); await expect(page.getByRole('heading', { name: 'Aprobada · esperamos los productos' })).toBeVisible();
 const before = await page.evaluate(() => JSON.parse(localStorage.getItem('storecore.commercial-demo.v1')!).products.slice(0, 2).map((product: {onHand:number}) => product.onHand));
 await cta(page, `return-outcome-${returnId}-DEMO-001:standard`).selectOption('sellable'); await cta(page, `return-outcome-${returnId}-DEMO-002:standard`).selectOption('quarantine'); await cta(page, `return-inspect-${returnId}`).click(); await expect(page.getByRole('heading', { name: 'Inspeccionada · reintegro pendiente' })).toBeVisible();
 const inspected = await page.evaluate(() => JSON.parse(localStorage.getItem('storecore.commercial-demo.v1')!).products.slice(0, 2).map((product: {onHand:number}) => product.onHand)); expect(inspected).toEqual([before[0] + 2, before[1]]);
 await cta(page, `return-refund-${returnId}`).click(); await expect(page.getByRole('heading', { name: 'Reembolso simulado completado' })).toBeVisible(); await expect(cta(page, `return-refund-${returnId}`)).toHaveCount(0);
 await page.reload(); const final = await page.evaluate(() => JSON.parse(localStorage.getItem('storecore.commercial-demo.v1')!)); expect(final.products.slice(0, 2).map((product: {onHand:number}) => product.onHand)).toEqual(inspected); expect(final.orders.at(-1).returns[0].lines.map((line: { quantity:number }) => line.quantity)).toEqual([2, 1]);
 await page.screenshot({ path: info.outputPath('admin-refund.png'), fullPage: true }); expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
 await login(page); await page.goto(`/demo/customer/orders/${id}`); await expect(page.getByRole('heading', { name: 'Reembolso simulado completado' })).toBeVisible(); for (const alert of final.postSaleAlerts) { await cta(page, `return-alert-${alert.id}`).click(); await expect(page).toHaveURL(new RegExp(`/customer/orders/${id}$`)); } await cta(page, 'order-receipt').click(); await expect(page.getByRole('dialog')).toContainText('SIM-REFUND'); await info.attach('post-sale-data', { body: JSON.stringify({ id, returnId, before, inspected, refund: final.orders.at(-1).returns[0], alerts: final.postSaleAlerts, executedPostSaleActions: ['request', 'quantity', 'reason', 'queue', 'decision-note', 'approve', 'sellable-inspection', 'quarantine-inspection', 'inspect', 'refund', 'all-alert-destinations', 'receipt'] }, null, 2), contentType: 'application/json' });
});

test('rejected return exposes reason, retains stock and refund totals, and isolates other buyer', async ({ page }, info) => {
 await login(page, false, 'cliente2@demo.invalid'); await page.goto('/demo/customer/orders/DEMO-102'); await cta(page, 'return-quantity-DEMO-003:standard').fill('1'); await cta(page, 'return-reason-DEMO-003:standard').selectOption('changed-mind'); await cta(page, 'return-request').click(); await expect(page.getByRole('heading', { name: 'Solicitud enviada' })).toBeVisible();
 await page.locator('[data-cta^="return-cancel-"]').click(); await expect(page.getByRole('heading',{name:'Solicitud cancelada por el comprador'})).toBeVisible(); await cta(page, 'return-quantity-DEMO-003:standard').fill('1'); await cta(page, 'return-reason-DEMO-003:standard').selectOption('changed-mind'); await cta(page, 'return-request').click();
 await login(page); await page.goto('/demo/customer/orders/DEMO-102'); await expect(page.getByRole('heading', { name: 'Pedido no disponible' })).toBeVisible(); await expect(page.locator('sc-demo-postsale article')).toHaveCount(0);
 await login(page, true); await page.goto('/demo/user/orders/DEMO-102'); const id = (await page.locator('[data-cta^="return-reject-"]').getAttribute('data-cta'))!.slice('return-reject-'.length);
 await cta(page, `return-reject-${id}`).click(); await expect(page.getByRole('alert')).toContainText('motivo'); await cta(page, `return-note-${id}`).fill('Solicitud fuera del plazo de la política de muestra'); await cta(page, `return-reject-${id}`).click(); await expect(page.getByRole('heading', { name: 'Solicitud rechazada' })).toBeVisible(); await expect(page.locator('[data-cta^="return-refund-"]')).toHaveCount(0);
 await login(page, false, 'cliente2@demo.invalid'); await page.goto('/demo/customer/orders/DEMO-102'); await expect(page.getByText('Solicitud fuera del plazo de la política de muestra', { exact: false }).first()).toBeVisible(); await expect(page.getByRole('heading', { name: 'Solicitar una devolución' })).toBeVisible(); await expect(page.getByRole('heading', { name: 'Solicitud rechazada' })).toBeVisible();
 const data = await page.evaluate(() => JSON.parse(localStorage.getItem('storecore.commercial-demo.v1')!)); expect(data.orders[2].returns.every((request:{refundId?:string})=>!request.refundId)).toBe(true); expect(data.movements).toHaveLength(0); await info.attach('rejection-data-trace', { body: JSON.stringify({ returns: data.orders[2].returns, movements: data.movements, executedPostSaleActions: ['buyer-cancel', 'reject-missing-note', 'reject-with-note', 'other-buyer-isolation', 'buyer-recovery'] }, null, 2), contentType: 'application/json' });
});
