import { expect, Page, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const cta=(page:Page,id:string)=>page.locator(`[data-cta="${id}"]`);
async function login(page:Page,admin=false){ await page.goto('/demo/login'); await page.getByLabel('Contraseña',{exact:true}).fill('demo'); await cta(page,'login-submit').click(); await cta(page,admin?'login-admin':'login-customer').click(); }
test.beforeEach(async({page})=>{ await page.route('**/*',route=>{ const url=new URL(route.request().url()); expect(url.hostname).toBe('127.0.0.1'); expect(url.pathname.startsWith('/api')).toBe(false); return route.continue(); }); });

test('admin creates open variants → buyer multi-variant cart → immutable order → inventory',async({page},info)=>{
 test.setTimeout(60000); await login(page,true); await page.goto('/demo/user/catalog'); await cta(page,'admin-product-create').click();
 await page.locator('[name="sku"]').fill('OPEN-CATALOG'); await page.locator('[name="name"]').fill('Producto con atributos abiertos'); await page.locator('[name="brand"]').fill('Marca nueva'); await page.locator('[name="category"]').fill('Categoría nueva'); await page.locator('[name="description"]').fill('Dos variantes con precios, stock e imágenes diferentes.');
 await page.locator('[name="variant-name-0"]').fill('Azul M'); await page.locator('[name="variant-price-0"]').fill('100'); await page.locator('[name="variant-stock-0"]').fill('3');
 await cta(page,'variant-attribute-add-0').click(); await page.locator('[name="attr-name-0-1"]').fill('Color'); await page.locator('[name="attr-value-0-1"]').fill('Azul');
 await cta(page,'product-image-add').click(); await page.locator('[name^="product-alt-"]').fill('Producto azul, vista principal');
 await cta(page,'product-image-add').click(); await page.locator('[name^="product-image-"]').nth(1).selectOption('/assets/demo/DEMO-002.svg'); await page.locator('[name^="product-alt-"]').nth(1).fill('Accesorios del producto');
 await cta(page,'variant-image-add-0').click(); await page.locator('[name^="variant-alt-0-"]').fill('Variante azul');
 await cta(page,'product-variant-add').click(); await page.locator('[name="variant-name-1"]').fill('Rojo L'); await page.locator('[name="variant-price-1"]').fill('150'); await page.locator('[name="variant-stock-1"]').fill('2'); await cta(page,'variant-attribute-add-1').click(); await page.locator('[name="attr-name-1-0"]').fill('Color'); await page.locator('[name="attr-value-1-0"]').fill('Rojo'); await cta(page,'variant-image-add-1').click(); await page.locator('[name^="variant-image-1-"]').selectOption('/assets/demo/DEMO-003.svg'); await page.locator('[name^="variant-alt-1-"]').fill('Variante roja');
 await cta(page,'product-save').click(); await expect(page.getByRole('dialog')).not.toBeVisible(); await page.reload(); await expect(page.locator('table')).toContainText('Rojo L');
 await login(page); await page.goto('/demo/catalog/OPEN-CATALOG'); const choices=await cta(page,'product-variant').locator('option').evaluateAll(options=>options.map(option=>(option as HTMLOptionElement).value)); expect(choices).toHaveLength(2);
 await expect(page.locator('.large-price')).toContainText('100'); await cta(page,'product-add-cart').click(); await cta(page,'product-variant').selectOption(choices[1]); await expect(page.locator('.large-price')).toContainText('150'); await expect(page.locator('.product-art.large img')).toHaveAttribute('alt','Variante roja'); await cta(page,'product-add-cart').click(); await cta(page,'product-add-cart').click(); await cta(page,'product-review-cart').click();
 await expect(page.locator('.cart-line')).toHaveCount(2); await page.goto('/demo/catalog/DEMO-007'); await cta(page,'product-add-cart').click(); await cta(page,'product-review-cart').click(); await expect(page.locator('.cart-line')).toHaveCount(3); await cta(page,'cart-remove-DEMO-007:standard').click(); await expect(page.locator('.cart-line')).toHaveCount(2); await expect(page.locator('.total')).toContainText('400'); await page.locator('.cart-line').first().getByLabel('Cantidad').fill('2'); await expect(page.locator('.cart-line').last().getByLabel('Cantidad')).toHaveValue('2'); await expect(page.locator('.total')).toContainText('500'); await page.reload(); await expect(page.locator('.cart-line')).toHaveCount(2);
 await cta(page,'cart-checkout').click(); await page.getByRole('radio').check(); await cta(page,'checkout-step-next').click(); await cta(page,'checkout-delivery-method').selectOption('pickup'); await cta(page,'checkout-step-next').click(); await cta(page,'checkout-confirm').click(); await expect(page).toHaveURL(/checkout\/result/); const orderId=page.url().split('/').at(-1)!; await expect(page.locator('.summary-row.total')).toContainText('500');
 await login(page,true); await page.goto('/demo/user/inventory?q=OPEN-CATALOG'); await expect(page.locator('table')).toContainText('Azul M'); await expect(page.locator('table')).toContainText('1 disponibles'); await expect(page.locator('table')).toContainText('0 disponibles'); await cta(page,'inventory-adjust-OPEN-CATALOG').click(); await cta(page,'inventory-variant').selectOption(choices[1]); await page.getByLabel('Unidades').fill('1'); await page.getByLabel('Motivo',{exact:true}).fill('Reposición de variante roja'); await cta(page,'adjustment-save').click();
 await page.goto('/demo/user/catalog?q=OPEN-CATALOG'); await cta(page,'admin-product-edit-OPEN-CATALOG').click(); await page.locator('[name="variant-name-1"]').fill('Nombre posterior'); await page.locator('[name="variant-price-1"]').fill('200'); await cta(page,'product-save').click();
 await login(page); await page.goto(`/demo/customer/orders/${orderId}`); await expect(page.locator('.summary-row.total')).toContainText('500'); await expect(page.locator('main')).toContainText('Rojo L'); await expect(page.locator('main')).not.toContainText('Nombre posterior');
 await info.attach('variant-data-trace',{body:JSON.stringify({created:choices,cart:{lines:2,quantities:[2,2],totalMinor:50000},stockAfterSale:[1,0],stockAfterAdjustment:[1,1],historicalTotalMinor:50000},null,2),contentType:'application/json'});
});

for(const width of [390,768,1440]) test(`variant editor and gallery keyboard responsive ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:900}); await login(page,true); await page.goto('/demo/user/catalog'); await cta(page,'admin-product-edit-DEMO-001').click(); await expect(page.getByRole('dialog')).toBeVisible(); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true); await page.screenshot({path:info.outputPath('variant-editor.png'),fullPage:true}); expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]); await page.keyboard.press('Escape'); await expect(cta(page,'admin-product-edit-DEMO-001')).toBeFocused();
 await login(page); await page.goto('/demo/catalog/DEMO-001'); const src=await page.locator('.product-art.large img').getAttribute('src'); await cta(page,'gallery-1').click(); await expect(page.locator('.product-art.large img')).not.toHaveAttribute('src',src!); await cta(page,'gallery-zoom').focus(); await page.keyboard.press('Enter'); await expect(page.getByRole('dialog')).toBeVisible(); await expect(page.locator('.zoom-image')).toHaveAttribute('src',await page.locator('.product-art.large img').getAttribute('src') ?? ''); await page.keyboard.press('Escape'); await expect(cta(page,'gallery-zoom')).toBeFocused(); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true); await page.screenshot({path:info.outputPath('variant-pdp.png'),fullPage:true}); expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
});
